#!/usr/bin/env python3
"""Generate RTL constants and review artifacts from the M0 Python authority."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
from enum import IntEnum

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in __import__("sys").path:
    __import__("sys").path.insert(0, str(ROOT))
from compiler.v3 import architecture_scaling as scaling
from compiler.v3 import architecture_configuration as architecture
from compiler.v3 import context_isa as isa
from compiler.v3 import m3_control_image
from compiler.v3 import m11_program_images
from compiler.v3 import modulo_mapping_graph as mmg
from compiler.v3 import reconstruction_graphs as graphs
from compiler.v3 import run_configuration
from compiler.v3 import scheduled_context_compiler as context_compiler

def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()

def define(name: str, value: int, width: int | None = None) -> str:
    encoded = str(value) if width is None else f"{width}'d{value}"
    return f"`define {name:<48} {encoded}"

def enum_lines(prefix: str, enum_type: type[IntEnum], width: int) -> list[str]:
    return [define(f"RECON_{prefix}_{item.name}", int(item), width) for item in enum_type]


def field_lines(prefix: str, layout: dict[str, isa.Field]) -> list[str]:
    lines = []
    for name, field in layout.items():
        field_name = f"RECON_{prefix}_FIELD_{name.upper()}"
        lines.extend([
            define(f"{field_name}_LSB", field.lsb),
            define(f"{field_name}_W", field.width),
        ])
    return lines

def architecture_parameters() -> str:
    configuration = architecture.load()
    topology = configuration["topology"]
    storage = configuration["context_storage"]
    memory = configuration["memory"]
    numeric = configuration["numeric_profiles"]
    profiles = {profile["name"]: profile for profile in numeric["profiles"]}
    active = profiles[numeric["active"]]
    candidate = profiles[numeric["closure_candidate"]]
    active_energy_shift = 2 * ((active["solver_fraction_bits"] - 19) -
                               (active["data_fraction_bits"] - 14))
    candidate_energy_shift = 2 * ((candidate["solver_fraction_bits"] - 19) -
                                  (candidate["data_fraction_bits"] - 14))
    if active_energy_shift < 0 or candidate_energy_shift < 0:
        raise ValueError("negative certificate energy scaling is unsupported in RTL")
    for profile in (active, candidate):
        max_data_exponent = 17 - (
            profile["solver_fraction_bits"] - profile["data_fraction_bits"]) - 1
        if max_data_exponent != run_configuration.PHI_DATA_NORMALIZER_MAX_EXPONENT:
            raise ValueError("numeric profile changes the legal Phi data exponent range")
    lines = [
        "`ifndef ARCHITECTURE_PARAMETERS_VH",
        "`define ARCHITECTURE_PARAMETERS_VH",
        "// Generated by compiler/v3/generate_architecture_package.py. Do not edit.",
        define("RECON_ARCHITECTURE_REVISION", configuration["architecture_revision"], 8),
        define("RECON_RTL_MINOR_REVISION", configuration["rtl_minor_revision"], 8),
        define("RECON_REGISTER_MAP_REVISION", 3, 8),
        define("RECON_CONTEXT_FORMAT_REVISION", isa.CONTEXT_FORMAT_REVISION, 8),
        define("RECON_RUN_CONFIGURATION_REVISION", run_configuration.REVISION, 8),
        define("RECON_DATA_W", active["data_width"]),
        define("RECON_DATA_F", active["data_fraction_bits"]),
        define("RECON_SOLVER_W", active["solver_width"]),
        define("RECON_SOLVER_F", active["solver_fraction_bits"]),
        define("RECON_LOCAL_ACC_W", scaling.LOCAL_ACC_W),
        define("RECON_ACC_W", active["accumulator_width"]),
        define("RECON_NUMERIC_PROFILE_ID", active["id"]),
        define("RECON_SCALAR_DIVIDE_LATENCY", active["scalar_divide_latency"]),
        define("RECON_STRICT_NORMAL_RESIDUAL_SHIFT",
               active["strict_normal_residual_shift"], 5),
        define("RECON_CERT_ABSOLUTE_FLOOR", 16384 << active_energy_shift),
        define("RECON_CERT_SUPPORT_SMALL_SHIFT", 11 + active_energy_shift),
        define("RECON_CERT_SUPPORT_LARGE_SHIFT", 12 + active_energy_shift),
        define("RECON_CERT_MEASUREMENT_SHIFT", 10 + active_energy_shift),
        define("RECON_CANDIDATE_DATA_W", candidate["data_width"]),
        define("RECON_CANDIDATE_DATA_F", candidate["data_fraction_bits"]),
        define("RECON_CANDIDATE_SOLVER_W", candidate["solver_width"]),
        define("RECON_CANDIDATE_SOLVER_F", candidate["solver_fraction_bits"]),
        define("RECON_CANDIDATE_ACC_W", candidate["accumulator_width"]),
        define("RECON_CANDIDATE_NUMERIC_PROFILE_ID", candidate["id"]),
        define("RECON_CANDIDATE_SCALAR_DIVIDE_LATENCY",
               candidate["scalar_divide_latency"]),
        define("RECON_CANDIDATE_STRICT_NORMAL_RESIDUAL_SHIFT",
               candidate["strict_normal_residual_shift"], 5),
        define("RECON_CANDIDATE_CERT_ABSOLUTE_FLOOR",
               16384 << candidate_energy_shift),
        define("RECON_CANDIDATE_CERT_SUPPORT_SMALL_SHIFT",
               11 + candidate_energy_shift),
        define("RECON_CANDIDATE_CERT_SUPPORT_LARGE_SHIFT",
               12 + candidate_energy_shift),
        define("RECON_CANDIDATE_CERT_MEASUREMENT_SHIFT",
               10 + candidate_energy_shift),
        define("RECON_N_MAX", 1024), define("RECON_M_MAX", 128),
        define("RECON_K_MAX", 32), define("RECON_CAND_MAX", 64),
        define("RECON_WORK_MAX", 96),
        define("RECON_CLUSTER_COUNT", topology["cluster_count"]),
        define("RECON_PE_ROWS", topology["rows_per_cluster"]),
        define("RECON_PE_COLUMNS", topology["columns_per_cluster"]),
        define("RECON_PE_PER_CLUSTER", topology["rows_per_cluster"] *
               topology["columns_per_cluster"]),
        define("RECON_PE_COUNT", topology["cluster_count"] *
               topology["rows_per_cluster"] * topology["columns_per_cluster"]),
        define("RECON_PREDICATE_COUNT", scaling.PREDICATE_COUNT),
        define("RECON_SHARED_VECTOR_LANES", scaling.SHARED_VECTOR_ARITHMETIC_LANES),
        define("RECON_SHARED_VECTOR_MULTIPLY_II", scaling.SHARED_VECTOR_MULTIPLY_II),
        define("RECON_SHARED_VECTOR_RESULTS_PER_CYCLE", scaling.SHARED_VECTOR_RESULTS_PER_CYCLE),
        define("RECON_TILE_CONTEXT_W", isa.TILE_CONTEXT_WIDTH),
        define("RECON_ARRAY_CONTROL_CONTEXT_W", isa.ARRAY_CONTROL_CONTEXT_WIDTH),
        define("RECON_STREAM_CONTEXT_W", isa.STREAM_CONTEXT_WIDTH),
        define("RECON_RESOURCE_CONTEXT_W", isa.RESOURCE_CONTEXT_WIDTH),
        define("RECON_PHASE_INSTRUCTION_W", isa.PHASE_INSTRUCTION_WIDTH),
        define("RECON_MEMORY_CONFIGURATION_W", isa.MEMORY_CONFIGURATION_WIDTH),
        define("RECON_MEMORY_CONFIGURATION_COUNT", memory["memory_configuration_count"]),
        define("RECON_MEMORY_CONFIGURATION_READ_PORTS",
               memory["memory_configuration_read_ports"]),
        define("RECON_MEMORY_CONFIGURATION_READ_LATENCY",
               memory["memory_configuration_read_latency"]),
        define("RECON_CONTEXT_DEPTH", storage["context_depth"]),
        define("RECON_CONTEXT_IMAGE_BANKS", storage["image_banks"]),
        define("RECON_ARRAY_CONTEXT_COMMIT_PLANE",
               storage["array_context_commit_plane"], 4),
        define("RECON_PHASE_INSTRUCTION_COMMIT_PLANE",
               storage["phase_instruction_commit_plane"], 4),
        define("RECON_VECTOR_MEMORY_BANKS", memory["vector_bank_count"]),
        define("RECON_MEMORY_BANK_DEPTH", memory["vector_bank_depth"]),
        define("RECON_MEMORY_BANK_WORD_W", memory["vector_bank_word_width"]),
        define("RECON_DMA_DATA_W", memory["axi_data_width"]),
        define("RECON_PHI_GENERATOR_REVISION", 1, 8),
        define("RECON_PHI_GENERATOR_ROUNDS", 20),
        define("RECON_PHI_SIGNS_PER_CYCLE", scaling.PHI_SIGNS_PER_CYCLE),
        define("RECON_PHI_AMPLITUDE_SHIFT", 3),
        define("RECON_PHI_COLUMN_W", 10),
        define("RECON_PHI_ROW_PAIR_W", 3),
        define("RECON_PHI_ROW_BLOCK_W", 3),
        define("RECON_PHI_TAG_W", 8),
        define("RECON_PHI_REQUEST_QUEUE_DEPTH", 16),
        define("RECON_PHI_RESPONSE_QUEUE_DEPTH", 16),
        define("RECON_PHI_MAX_ROW_BLOCKS", 4),
        define("RECON_PHI_SUPPORT_CACHE_SLOTS", scaling.SHARED_VECTOR_RESULTS_PER_CYCLE * 12),
        define("RECON_PHI_CANDIDATE_CACHE_SLOTS", scaling.TOPK_PHYSICAL_DEPTH),
        define("RECON_PHI_SCALE_MANTISSA_W", 18),
        define("RECON_PHI_SCALE_EXPONENT_W", 5),
        define("RECON_PHI_NORMALIZER_LATENCY", 4),
        define("RECON_TOPK_COMPARE_LANES", scaling.TOPK_COMPARE_LANES),
        define("RECON_TOPK_PHYSICAL_DEPTH", scaling.TOPK_PHYSICAL_DEPTH),
        "`endif", ""]
    return "\n".join(lines)

def context_defs() -> str:
    lines = ["`ifndef CONTEXT_ISA_DEFS_VH", "`define CONTEXT_ISA_DEFS_VH",
             f"// Generated context ISA revision {isa.CONTEXT_FORMAT_REVISION}. Do not edit."]
    for prefix, enum_type, width in (
        ("TILE_OP", isa.TileOperation, 5),
        ("OPERAND_SOURCE", isa.OperandSource, 3),
        ("ROUTE_SOURCE", isa.RouteSource, 3),
        ("NEXT_PC_MODE", isa.NextPcMode, 3),
        ("PHASE_OP", isa.PhaseOperation, 3),
        ("PHASE_CONDITION", isa.PhaseCondition, 4),
        ("EXTERNAL_STREAM_SOURCE", isa.ExternalStreamSource, 2),
        ("PHI_COMMAND", isa.PhiStreamCommand, 2),
        ("RESOURCE_OP", isa.ResourceOperation, 5),
        ("RESOURCE_INPUT", isa.ResourceInput, 3),
        ("RESOURCE_OUTPUT", isa.ResourceOutput, 3),
        ("LOOP_LIMIT", isa.LoopLimitSource, 4),
        ("RESOURCE_COUNT", isa.ResourceCountSource, 4),
        ("STREAM_BOUNDARY", isa.StreamBoundary, 2),
        ("ELEMENT_FORMAT", isa.ElementFormat, 3),
        ("MEMORY_SPACE", isa.MemorySpace, 2),
        ("BANK_MODE", isa.BankMode, 3),
        ("PACKING_MODE", isa.PackingMode, 3)):
        lines.extend(enum_lines(prefix, enum_type, width))
    for prefix, layout in (
        ("TILE", isa.TILE_FIELDS),
        ("ARRAY_CONTROL", isa.ARRAY_CONTROL_FIELDS),
        ("STREAM", isa.STREAM_FIELDS),
        ("PHASE", isa.PHASE_FIELDS),
        ("RESOURCE", isa.RESOURCE_FIELDS),
        ("MEMORY_CONFIGURATION", isa.MEMORY_CONFIGURATION_FIELDS),
    ):
        lines.extend(field_lines(prefix, layout))
    lines.extend(["`endif", ""])
    return "\n".join(lines)


def architecture_guard_defs() -> str:
    configuration = architecture.load()
    errors = configuration["reservation_guard"]["error_codes"]
    tile_mask = sum(1 << int(item) for item in isa.TileOperation)
    resource_mask = sum(1 << int(item) for item in isa.ResourceOperation)
    implemented_resource_mask = sum(
        1 << record["code"] for record in configuration["resource_operations"]
        if record["status"] == "implemented")
    reserved_fault_mask = sum(
        1 << record["code"] for record in configuration["resource_operations"]
        if record["status"] == "reserved")
    route_mask = sum(1 << int(item) for item in isa.RouteSource
                     if item != isa.RouteSource.ROW_OR_COLUMN_EXPRESS)
    next_pc_mask = sum(1 << int(item) for item in isa.NextPcMode)
    phase_operation_mask = sum(1 << int(item) for item in isa.PhaseOperation)
    phase_condition_mask = sum(1 << int(item) for item in isa.PhaseCondition)
    execution = configuration["execution_context"]
    lines = [
        "`ifndef ARCHITECTURE_GUARD_DEFS_VH",
        "`define ARCHITECTURE_GUARD_DEFS_VH",
        "// Generated from architecture_configuration.json. Do not edit.",
        f"`define RECON_ARCHITECTURE_HASH 256'h{architecture.configuration_hash(configuration)}",
        f"`define RECON_TILE_OPERATION_LEGAL_MASK 32'h{tile_mask:08x}",
        f"`define RECON_RESOURCE_OPERATION_LEGAL_MASK 32'h{resource_mask:08x}",
        f"`define RECON_RESOURCE_OPERATION_IMPLEMENTED_MASK 32'h{implemented_resource_mask:08x}",
        f"`define RECON_RESOURCE_OPERATION_RESERVED_FAULT_MASK 32'h{reserved_fault_mask:08x}",
        f"`define RECON_ROUTE_SOURCE_LEGAL_MASK 8'h{route_mask:02x}",
        f"`define RECON_NEXT_PC_MODE_LEGAL_MASK 8'h{next_pc_mask:02x}",
        f"`define RECON_PHASE_OPERATION_LEGAL_MASK 8'h{phase_operation_mask:02x}",
        f"`define RECON_PHASE_CONDITION_LEGAL_MASK 16'h{phase_condition_mask:04x}",
        define("RECON_PHASE_ENTRY_PC", execution["phase_entry_pc"], 8),
    ]
    for name, code in errors.items():
        lines.append(define(f"RECON_CONTEXT_ERROR_{name.upper()}", code, 8))
    lines.extend(["`endif", ""])
    return "\n".join(lines)

def run_configuration_defs() -> str:
    lines = ["`ifndef RUN_CONFIGURATION_DEFS_VH", "`define RUN_CONFIGURATION_DEFS_VH",
             f"// Generated run-configuration block revision {run_configuration.REVISION}. Do not edit.",
             define("RECON_RUN_CONFIGURATION_MAGIC", run_configuration.MAGIC, 16),
             define("RECON_RUN_CONFIGURATION_WORDS", run_configuration.WORD_COUNT),
             define("RECON_RUN_CONFIGURATION_BYTES", run_configuration.BYTE_COUNT),
             define("RECON_RUN_CONFIGURATION_BITS", run_configuration.WORD_COUNT * 32)]
    lines.append(define("RECON_PHI_DATA_NORMALIZER_MAX_EXPONENT",
                        run_configuration.PHI_DATA_NORMALIZER_MAX_EXPONENT))
    lines.extend(enum_lines("REFINEMENT_PROFILE", run_configuration.RefinementProfile, 2))
    lines.extend(enum_lines("MATRIX_KIND", run_configuration.MatrixKind, 2))
    lines.extend(enum_lines("RESULT_MODE", run_configuration.ResultMode, 2))
    lines.extend(enum_lines("TERMINATION_MODE", run_configuration.TerminationMode, 1))
    lines.extend(["`define RECON_RUN_CONFIGURATION_W2_REFINEMENT_PROFILE_MSB 31",
                  "`define RECON_RUN_CONFIGURATION_W2_REFINEMENT_PROFILE_LSB 30",
                  "`define RECON_RUN_CONFIGURATION_W2_TERMINATION_MODE_MSB 29",
                  "`define RECON_RUN_CONFIGURATION_W2_TERMINATION_MODE_LSB 29",
                  "`endif", ""])
    return "\n".join(lines)

def disassembly() -> str:
    configuration = architecture.load()
    reserved = {
        record["name"] for record in configuration["resource_operations"]
        if record["status"] == "reserved"
    }
    tile = "\n".join(f"| {int(x)} | `{x.name}` |" for x in isa.TileOperation)
    resource = "\n".join(
        f"| {int(x)} | `{x.name}{'_RESERVED' if x.name in reserved else ''}` |"
        for x in isa.ResourceOperation)
    return (f"# Context ISA revision {isa.CONTEXT_FORMAT_REVISION} generated disassembly\n\n"
            "Undefined tile encoding 16 is the illegal retired multiply opcode.\n\n"
            "## Tile operations\n\n| Code | Operation |\n| ---: | --- |\n" + tile
            + "\n\n## Shared resource operations\n\n| Code | Operation |\n| ---: | --- |\n"
            + resource + "\n")

def transaction_golden() -> dict:
    segments = dict(context_compiler.restricted_refinement_resource_segments())
    certificate_path = [
        ("forward_Ap", isa.ResourceContext()),
        *segments["restricted_refinement_pre_transpose"],
        ("transpose_ATr", isa.ResourceContext()),
        *segments["restricted_refinement_certificate"],
    ]
    continuation_tail = segments["restricted_refinement_continuation"]

    def encode(sequence: list[tuple[str, isa.ResourceContext]]) -> list[dict]:
        encoded = []
        for cycle, (stage, resource) in enumerate(sequence):
            final = cycle == len(sequence) - 1
            control = isa.ArrayControlContext(
                next_pc=cycle + 1 if not final else 0,
                next_pc_mode=(isa.NextPcMode.SEQUENTIAL if not final
                              else isa.NextPcMode.RETURN_TO_PHASE),
                loop_limit_select=isa.LoopLimitSource.REFINEMENT_ITERATION_LIMIT,
                cluster_enable_mask=0b11, routine_done=int(final),
                safe_abort_point=int(final),
                guaranteed_commit=int(resource.operation == isa.ResourceOperation.NOP),
            )
            isa.validate_context_bundle(control, isa.StreamContext(), resource)
            encoded.append({"cycle": cycle, "stage": stage,
                            "array_control_word": isa.pack_array_control(control),
                            "resource_word": isa.pack_resource(resource)})
        return encoded

    cycles = encode(certificate_path)
    continuation = encode(continuation_tail)
    return {
        "schema": "cscgra-v3-context-transaction-golden-v2",
        "context_revision": isa.CONTEXT_FORMAT_REVISION,
        "routine": "restricted_refinement_iteration",
        "resource_control": "compiler_scheduled_implemented_resources_only",
        "blocked_stages": [],
        "cycles": cycles,
        "continuation_tail": continuation,
        "scalar_register_contract": {
            "certificate_entry": {"rf0": "gamma_reference", "rf1": "gamma_new"},
            "continuation_beta": "RF1/RF0 -> RF0",
            "continuation_rotate": "M5 gamma shadow restores gamma_new -> RF0 after update_p",
        },
    }

def generate() -> None:
    include = ROOT / "rtl" / "v3" / "include"
    reports = ROOT / "reports" / "v3"
    include.mkdir(parents=True, exist_ok=True)
    reports.mkdir(parents=True, exist_ok=True)
    configuration = architecture.load()
    compiled_contexts = context_compiler.payload()
    outputs = {
        include / "architecture_parameters.vh": architecture_parameters(),
        include / "context_isa_defs.vh": context_defs(),
        include / "architecture_guard_defs.vh": architecture_guard_defs(),
        include / "run_configuration_defs.vh": run_configuration_defs(),
        reports / "context_isa_disassembly.md": disassembly(),
        reports / "architecture_scaling.json": json.dumps(scaling.payload(), indent=2, sort_keys=True) + "\n",
        reports / "reconstruction_graphs.json": json.dumps(graphs.payload(), indent=2, sort_keys=True) + "\n",
        reports / "context_transaction_golden.json": json.dumps(
            transaction_golden(), indent=2, sort_keys=True) + "\n",
        reports / "architecture_latency_ii.json": json.dumps(
            architecture.latency_ii_payload(configuration), indent=2,
            sort_keys=True) + "\n",
        reports / "mrrg_base.json": json.dumps(
            architecture.mrrg_payload(configuration), indent=2,
            sort_keys=True) + "\n",
        reports / "modulo_mapping_graphs.json": json.dumps(
            mmg.payload(), indent=2, sort_keys=True) + "\n",
        reports / "scheduled_context_library.json": json.dumps(
            compiled_contexts, indent=2, sort_keys=True) + "\n",
        reports / "m3_control_image.json": json.dumps(
            m3_control_image.payload(), indent=2, sort_keys=True) + "\n",
        reports / "m11_program_images.json": json.dumps(
            m11_program_images.payload(), indent=2, sort_keys=True) + "\n",
        reports / "m11_program_readiness.json": json.dumps(
            m11_program_images.readiness_payload(), indent=2,
            sort_keys=True) + "\n",
        ROOT / "verification" / "v3" / "m3" / "generated" /
        "m3_control_image.vh": m3_control_image.sv_include(),
    }
    for name, content in context_compiler.mem_files(compiled_contexts).items():
        outputs[reports / "context_images" / name] = content
    for name, content in m11_program_images.mem_files().items():
        outputs[reports / "context_images" / name] = content
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    authority = [
        ROOT / "compiler" / "v3" / "generate_architecture_package.py",
        ROOT / "compiler" / "v3" / "architecture_scaling.py",
        ROOT / "compiler" / "v3" / "architecture_configuration.py",
        ROOT / "compiler" / "v3" / "architecture_configuration.json",
        ROOT / "compiler" / "v3" / "context_isa.py",
        ROOT / "compiler" / "v3" / "modulo_mapping_graph.py",
        ROOT / "compiler" / "v3" / "m11_program_images.py",
        ROOT / "compiler" / "v3" / "reconstruction_graphs.py",
        ROOT / "compiler" / "v3" / "run_configuration.py",
        ROOT / "compiler" / "v3" / "scheduled_context_compiler.py",
        ROOT / "models" / "v3" / "hardware.py",
    ]
    manifest = {
        "schema": "cscgra-v3-m36-architecture-manifest-v1",
        "architecture_configuration_sha256": architecture.configuration_hash(configuration),
        "context_revision": isa.CONTEXT_FORMAT_REVISION,
        "run_configuration_revision": run_configuration.REVISION,
        "macroblocks": graphs.payload()["architecture"]["macroblocks"],
        "authority_sha256": {str(p.relative_to(ROOT)).replace("\\", "/"): digest(p)
                             for p in authority},
        "generated_sha256": {str(p.relative_to(ROOT)).replace("\\", "/"): digest(p)
                             for p in outputs},
    }
    (reports / "architecture_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n")

def main() -> None:
    argparse.ArgumentParser().parse_args()
    generate()
    print("generated v3 M3.6 architecture package")

if __name__ == "__main__":
    main()
