`ifndef CSR_COMMIT_INTERFACE_VH
`define CSR_COMMIT_INTERFACE_VH
`define CSR_COMMIT_S_W 27
`define CSR_COMMIT_X_W 24
`define CSR_COMMIT_SHIFT 2
`define CSR_COMMIT_LANES 32
`define CSR_COMMIT_CAPACITY 96
`define CSR_COMMIT_INDEX_W 10
`define CSR_COMMIT_FORMAT 1
`define CSR_COMMIT_FAULT_NONE 0
`define CSR_COMMIT_FAULT_MODE 1
`define CSR_COMMIT_FAULT_SUPPORT 2
`define CSR_COMMIT_FAULT_IDENTITY 3
`define CSR_COMMIT_FAULT_STREAM 4
`define CSR_COMMIT_FAULT_NUMERIC 5
`define CSR_COMMIT_FAULT_CERTIFICATE 6
`define CSR_COMMIT_FAULT_CANCEL 7
`define CSR_COMMIT_FAULT_READ 8
`endif
