`ifndef CSR_OPERATOR_DEFS_VH
`define CSR_OPERATOR_DEFS_VH
`define CSR_OP_REV 1
`define CSR_OP_DESCRIPTORS 16
`define CSR_OP_ADDRESS_MODE 1
`define CSR_OP_MODE_LSB 0
`define CSR_OP_MODE_W 2
`define CSR_OP_TRANS_LSB 2
`define CSR_OP_TRANS_W 1
`define CSR_OP_ROWS_LSB 3
`define CSR_OP_ROWS_W 8
`define CSR_OP_COLS_LSB 11
`define CSR_OP_COLS_W 11
`define CSR_OP_VEC_BASE_LSB 22
`define CSR_OP_VEC_BASE_W 12
`define CSR_OP_VEC_PLANE_LSB 34
`define CSR_OP_VEC_PLANE_W 2
`define CSR_OP_SCALE_LSB 36
`define CSR_OP_SCALE_W 18
`define CSR_OP_KEY_LSB 54
`define CSR_OP_KEY_W 128
`define CSR_OP_MAT_GENERATION_LSB 182
`define CSR_OP_MAT_GENERATION_W 32
`define CSR_OP_VEC_GENERATION_LSB 214
`define CSR_OP_VEC_GENERATION_W 32
`define CSR_OP_JOB_LSB 246
`define CSR_OP_JOB_W 16
`define CSR_OP_FMT_LSB 262
`define CSR_OP_FMT_W 8
`define CSR_OP_DESC_W 270
`endif
