+incdir+rtl/v3/include
rtl/v3/host_interface/axi4lite_slave.v
rtl/v3/host_interface/reconstruction_csr.v
rtl/v3/host_interface/m13_loader_aperture.v
rtl/v3/reconstruction_control/configuration_fetch_unit.v
rtl/v3/reconstruction_control/configuration_check_unit.v
rtl/v3/reconstruction_control/active_configuration_store.v
rtl/v3/reconstruction_control/reconstruction_configuration_unit.v
rtl/v3/reconstruction_control/reconstruction_phase_controller.v
rtl/v3/reconstruction_control/resident_execution_state.v
rtl/v3/context_control/context_write_certifier.v
rtl/v3/context_control/context_image_store.v
rtl/v3/context_control/memory_configuration_store.v
rtl/v3/context_control/context_reservation_guard.v
rtl/v3/context_control/array_context_sequencer.v
rtl/v3/data_movement/axi_read_burst_engine.v
rtl/v3/data_movement/axi_write_burst_engine.v
rtl/v3/data_movement/dma_request_arbiter.v
rtl/v3/data_movement/dma_element_normalizer.v
rtl/v3/data_movement/memory_dma_engine.v
rtl/v3/data_movement/scratchpad_preload_engine.v
rtl/v3/data_movement/scratchpad_residency_tracker.v
rtl/v3/data_movement/vector_scratchpad.v
rtl/v3/data_movement/scratchpad_subsystem.v
rtl/v3/data_movement/vector_stream_engine.v
rtl/v3/data_movement/scratchpad_word_codec.v
rtl/v3/data_movement/vector_codec_write_subsystem.v
rtl/v3/data_movement/vector_ingress_adapter.v
rtl/v3/data_movement/normalized_result_writeback.v
rtl/v3/data_movement/reconstruction_result_writer.v
rtl/v3/memory/recon_sdp_ram.v
rtl/v3/memory/recon_1w2r_ram.v
rtl/v3/memory/recon_epoch_slot_map.v
rtl/v3/memory/support_coefficient_stripe_store.v
rtl/v3/cgra/stream_context_router.v
rtl/v3/cgra/pe_alu.v
rtl/v3/cgra/phi_pe_alu.v
rtl/v3/cgra/pe_local_register_file.v
rtl/v3/cgra/registered_switchbox.v
rtl/v3/cgra/pe_tile.v
rtl/v3/cgra/phi_pe_tile.v
rtl/v3/cgra/cgra_row.v
rtl/v3/cgra/cgra_cluster.v
rtl/v3/cgra/cgra_cluster_pair.v
rtl/v3/cgra/cgra_result_buffer.v
rtl/v3/cgra/cgra_result_capture_adapter.v
rtl/v3/cgra/cgra_execution_fabric.v
rtl/v3/phi/phi_request_queue.v
rtl/v3/phi/threefry2x32_folded_pipeline.v
rtl/v3/phi/phi_symbol_builder.v
rtl/v3/phi/phi_response_gearbox.v
rtl/v3/phi/phi_symbol_generator.v
rtl/v3/phi/support_phi_symbol_cache.v
rtl/v3/phi/phi_stream_provider.v
rtl/v3/phi/phi_stream_subsystem.v
rtl/v3/phi/phi_operator_normalizer.v
rtl/v3/phi/phi_lane_normalization_flow.v
rtl/v3/phi/phi_column_flow.v
rtl/v3/arithmetic/cluster_reduction_unit.v
rtl/v3/arithmetic/global_reduction_merge.v
rtl/v3/arithmetic/reduction_pipeline.v
rtl/v3/arithmetic/scalar_register_file.v
rtl/v3/arithmetic/scalar_state_subsystem.v
rtl/v3/arithmetic/scalar_function_unit.v
rtl/v3/arithmetic/shared_vector_arithmetic_unit.v
rtl/v3/arithmetic/shared_vector_pipeline.v
rtl/v3/arithmetic/array_resource_router.v
rtl/v3/arithmetic/m5_arithmetic_subsystem.v
rtl/v3/selection/topk_selection_unit.v
rtl/v3/selection/proxy_candidate_collector.v
rtl/v3/selection/vector_candidate_serializer.v
rtl/v3/selection/candidate_stream_adapter.v
rtl/v3/selection/support_vector_rebuilder.v
rtl/v3/selection/support_refinement_adapter.v
rtl/v3/selection/support_workspace.v
rtl/v3/selection/support_state_manager.v
rtl/v3/selection/support_coefficient_remapper.v
rtl/v3/selection/m9b_support_subsystem.v
rtl/v3/refinement/certificate_limit_unit.v
rtl/v3/refinement/normal_residual_checker.v
rtl/v3/refinement/restricted_refinement_state.v
rtl/v3/debug/operator_fault_monitor.v
rtl/v3/debug/operator_fault_event_encoder.v
rtl/v3/debug/execution_profile_monitor.v
rtl/v3/debug/execution_event_profile_monitor.v
rtl/v3/integration/m8_resource_dispatcher.v
rtl/v3/integration/operator_flow_control.v
rtl/v3/integration/m8_operator_harness.v
rtl/v3/integration/m9b_n3_integration.v
rtl/v3/integration/m10_refinement_integration.v
rtl/v3/integration/m12_result_dma_integration.v
rtl/v3/integration/m12_lifecycle_top.v
rtl/v3/integration/m13_termination_monitor.v
rtl/v3/integration/m13_compute_lifecycle_integration.v
rtl/v3/integration/m13_zcu106_shell_core.v
rtl/v3/top/m1_control_top.v
rtl/v3/top/top.v
