#!/usr/bin/env python3
from __future__ import annotations
import json
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in __import__("sys").path:
    __import__("sys").path.insert(0, str(ROOT))
from models.v3 import hardware

SEED = 0x9A320826
K = 32

def rank_state(latest: dict[int, int]) -> list[tuple[int, int]]:
    width = max(latest, default=-1) + 1
    values = [0] * width
    present = set(latest)
    for index, score in latest.items():
        values[index] = score
    ranked = hardware._rank(values, len(values), set(range(width)) - present)
    return [(index, latest[index]) for index in ranked[:K]]

def payload() -> dict:
    rng = random.Random(SEED)
    candidates = [
        {"score": -10, "index": 5},
        {"score": 10, "index": 3},
        {"score": 7, "index": 1},
        {"score": -12, "index": 9},
        {"score": 12, "index": 2},
        {"score": 13, "index": 3},
        {"score": -(1 << 26), "index": 7},
        {"score": (1 << 26) - 1, "index": 6},
    ]
    used = {item["index"] for item in candidates}
    while len(candidates) < 48:
        index = rng.randrange(0, 128)
        score = rng.randrange(-(1 << 26), 1 << 26)
        candidates.append({"score": score, "index": index})
        used.add(index)
    latest: dict[int, int] = {}
    snapshots = []
    for item in candidates:
        latest.setdefault(item["index"], item["score"])
        snapshots.append(rank_state(latest))
    final = snapshots[-1]
    return {
        "schema": "cscgra-v3-m9a-topk-transaction-golden-v1",
        "seed": SEED,
        "k": K,
        "semantics": "descending absolute magnitude; lower index wins tie; duplicate index is ignored; first accepted value owns the index",
        "candidates": candidates,
        "snapshots": [[{"index": index, "score": score} for index, score in state]
                      for state in snapshots],
        "final": [{"index": index, "score": score} for index, score in final],
    }

def sv_literal(value: int) -> str:
    return f"-27'sd{-value}" if value < 0 else f"27'sd{value}"

def sv_include(data: dict) -> str:
    lines = [
        "// Generated by scripts/golden/generate_m9a_vectors.py. Do not edit.",
        "task load_m9a_golden;",
        "    begin",
        f"        golden_candidate_count = {len(data['candidates'])};",
        f"        golden_expected_count = {len(data['final'])};",
    ]
    for offset, item in enumerate(data["candidates"]):
        lines.append(f"        golden_candidate_score[{offset}] = {sv_literal(item['score'])};")
        lines.append(f"        golden_candidate_index[{offset}] = 10'd{item['index']};")
    for offset, item in enumerate(data["final"]):
        lines.append(f"        golden_expected_score[{offset}] = {sv_literal(item['score'])};")
        lines.append(f"        golden_expected_index[{offset}] = 10'd{item['index']};")
    lines.extend(["    end", "endtask", ""])
    return "\n".join(lines)

def main() -> None:
    data = payload()
    report = ROOT / "reports/v3/m9a_topk_transaction_golden.json"
    include = ROOT / "verification/v3/m9a/generated/m9a_golden.vh"
    report.parent.mkdir(parents=True, exist_ok=True)
    include.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    include.write_text(sv_include(data), encoding="utf-8")
    print(f"generated {len(data['candidates'])} M9a candidates; final count {len(data['final'])}")

if __name__ == "__main__":
    main()
