module tb_context_engine;
reg clk = 0;
reg [471:0] stim;
wire [0:0] rst;
wire [0:0] cancel;
wire [0:0] begin_valid;
wire [7:0] begin_rev;
wire [8:0] begin_depth;
wire [0:0] begin_verified;
wire [31:0] begin_generation;
wire [0:0] wr_valid;
wire [7:0] wr_pc;
wire [5:0] wr_bank;
wire [255:0] wr_data;
wire [0:0] wr_last;
wire [0:0] start_valid;
wire [7:0] start_pc;
wire [31:0] start_limit;
wire [15:0] start_job;
wire [7:0] start_fmt;
wire [2:0] predicates;
wire [0:0] addr_ready;
wire [0:0] addr_rsp_valid;
wire [0:0] addr_rsp_fault;
wire [15:0] addr_rsp_job;
wire [15:0] addr_rsp_tag;
wire [0:0] exec_ready;
wire [0:0] exec_rsp_valid;
wire [0:0] exec_rsp_fault;
wire [15:0] exec_rsp_job;
wire [15:0] exec_rsp_tag;
wire [7:0] exec_rsp_fmt;
wire [0:0] done_ready;
wire [0:0] begin_ready;
wire [0:0] wr_ready;
wire [0:0] image_ready;
wire [0:0] loading;
wire [3:0] load_fault;
wire [0:0] start_ready;
wire [0:0] addr_valid;
wire [2:0] addr_mode;
wire [23:0] addr_value;
wire [15:0] addr_stride;
wire [0:0] addr_rsp_ready;
wire [0:0] exec_valid;
wire [2047:0] exec_words;
wire [15:0] exec_job;
wire [15:0] exec_tag;
wire [7:0] exec_fmt;
wire [0:0] exec_last;
wire [0:0] exec_cancel;
wire [0:0] exec_rsp_ready;
wire [0:0] done_valid;
wire [3:0] done_fault;
wire [7:0] pc;
wire [31:0] retired;
wire [2:0] state_depth;
wire [63:0] state_remaining;
wire [0:0] state_fetch_valid;
wire [0:0] state_mem_valid;
assign {rst, cancel, begin_valid, begin_rev, begin_depth, begin_verified, begin_generation, wr_valid, wr_pc, wr_bank, wr_data, wr_last, start_valid, start_pc, start_limit, start_job, start_fmt, predicates, addr_ready, addr_rsp_valid, addr_rsp_fault, addr_rsp_job, addr_rsp_tag, exec_ready, exec_rsp_valid, exec_rsp_fault, exec_rsp_job, exec_rsp_tag, exec_rsp_fmt, done_ready} = stim;
context_engine dut (.clk(clk), .rst(rst), .cancel(cancel), .begin_valid(begin_valid), .begin_rev(begin_rev), .begin_depth(begin_depth), .begin_verified(begin_verified), .begin_generation(begin_generation), .wr_valid(wr_valid), .wr_pc(wr_pc), .wr_bank(wr_bank), .wr_data(wr_data), .wr_last(wr_last), .start_valid(start_valid), .start_pc(start_pc), .start_limit(start_limit), .start_job(start_job), .start_fmt(start_fmt), .predicates(predicates), .addr_ready(addr_ready), .addr_rsp_valid(addr_rsp_valid), .addr_rsp_fault(addr_rsp_fault), .addr_rsp_job(addr_rsp_job), .addr_rsp_tag(addr_rsp_tag), .exec_ready(exec_ready), .exec_rsp_valid(exec_rsp_valid), .exec_rsp_fault(exec_rsp_fault), .exec_rsp_job(exec_rsp_job), .exec_rsp_tag(exec_rsp_tag), .exec_rsp_fmt(exec_rsp_fmt), .done_ready(done_ready), .begin_ready(begin_ready), .wr_ready(wr_ready), .image_ready(image_ready), .loading(loading), .load_fault(load_fault), .start_ready(start_ready), .addr_valid(addr_valid), .addr_mode(addr_mode), .addr_value(addr_value), .addr_stride(addr_stride), .addr_rsp_ready(addr_rsp_ready), .exec_valid(exec_valid), .exec_words(exec_words), .exec_job(exec_job), .exec_tag(exec_tag), .exec_fmt(exec_fmt), .exec_last(exec_last), .exec_cancel(exec_cancel), .exec_rsp_ready(exec_rsp_ready), .done_valid(done_valid), .done_fault(done_fault), .pc(pc), .retired(retired));
assign state_depth = dut.sequencer.depth;
assign state_fetch_valid = dut.fetch_valid;
assign state_mem_valid = dut.mem_valid;
assign state_remaining[0 +: 16] = state_depth > 0 ? dut.sequencer.remaining[0] : 16'b0;
assign state_remaining[16 +: 16] = state_depth > 1 ? dut.sequencer.remaining[1] : 16'b0;
assign state_remaining[32 +: 16] = state_depth > 2 ? dut.sequencer.remaining[2] : 16'b0;
assign state_remaining[48 +: 16] = state_depth > 3 ? dut.sequencer.remaining[3] : 16'b0;
integer src, dst, count, cycle;
reg [4095:0] src_path, dst_path;
initial begin
if (!$value$plusargs("src=%s", src_path)) $fatal(1, "missing vectors");
if (!$value$plusargs("dst=%s", dst_path)) $fatal(1, "missing trace");
src = $fopen(src_path, "r"); dst = $fopen(dst_path, "w");
if (!src || !dst) $fatal(1, "cannot open files");
cycle = 0;
while (!$feof(src)) begin
count = $fscanf(src, "%h", stim);
if (count == 1) begin
#4;
$fdisplay(dst, "%0d 0 %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h", cycle, begin_ready, wr_ready, image_ready, loading, load_fault, start_ready, addr_valid, addr_mode, addr_value, addr_stride, addr_rsp_ready, exec_valid, exec_words, exec_job, exec_tag, exec_fmt, exec_last, exec_cancel, exec_rsp_ready, done_valid, done_fault, pc, retired, state_depth, state_remaining, state_fetch_valid, state_mem_valid);
clk = 1; #1;
$fdisplay(dst, "%0d 1 %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h", cycle, begin_ready, wr_ready, image_ready, loading, load_fault, start_ready, addr_valid, addr_mode, addr_value, addr_stride, addr_rsp_ready, exec_valid, exec_words, exec_job, exec_tag, exec_fmt, exec_last, exec_cancel, exec_rsp_ready, done_valid, done_fault, pc, retired, state_depth, state_remaining, state_fetch_valid, state_mem_valid);
#4; clk = 0; cycle = cycle + 1;
end else if (!$feof(src)) $fatal(1, "bad vector row");
end
$fclose(src); $fclose(dst);
$display("PASS cycles=%0d", cycle); $finish;
end
initial begin #100000000; $fatal(1, "timeout"); end
endmodule
