`ifndef CSR_PHI_INTERFACE_VH
`define CSR_PHI_INTERFACE_VH
`define CSR_PHI_MAX_ROWS 128
`define CSR_PHI_MAX_COLUMNS 1024
`define CSR_PHI_WORD_BITS 32
`define CSR_PHI_BANKS 8
`define CSR_PHI_BANK_DEPTH 512
`define CSR_PHI_ROWS_W 8
`define CSR_PHI_COLUMNS_W 11
`define CSR_PHI_COLUMN_W 10
`define CSR_PHI_ROW_BLOCK_W 2
`define CSR_PHI_ADDR_W 9
`define CSR_PHI_FAMILY 1
`define CSR_PHI_REVISION 2
`define CSR_PHI_JOB_TAG_W 16
`define CSR_PHI_OP_TAG_W 16
`define CSR_PHI_FORMAT_TAG_W 8
`define CSR_PHI_GENERATION_W 32
`define CSR_PHI_KEY_W 128
`define CSR_PHI_READ_TAG_W 16
`define CSR_PHI_FAULT_W 4
`define CSR_PHI_FAULT_NONE 0
`define CSR_PHI_FAULT_DESCRIPTOR 1
`define CSR_PHI_FAULT_FILL 2
`define CSR_PHI_FAULT_READ 3
`define CSR_PHI_TAPS 32'h80200003
`define CSR_PHI_DEFAULT_SEED 32'hDEADBEEF
`endif
