`timescale 1ns/1ps
`default_nettype none

`include "architecture_parameters.vh"

module m13_zcu106_shell_core #(
    parameter integer AXIL_AW = 12,
    parameter integer TAG_W = 8
)(
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ap_clk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_RESET ap_rst_n" *)
    input  wire ap_clk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ap_rst_n RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire ap_rst_n,

    input  wire [AXIL_AW-1:0] s_axi_control_awaddr,
    input  wire s_axi_control_awvalid,
    output wire s_axi_control_awready,
    input  wire [31:0] s_axi_control_wdata,
    input  wire [3:0] s_axi_control_wstrb,
    input  wire s_axi_control_wvalid,
    output wire s_axi_control_wready,
    output wire [1:0] s_axi_control_bresp,
    output wire s_axi_control_bvalid,
    input  wire s_axi_control_bready,
    input  wire [AXIL_AW-1:0] s_axi_control_araddr,
    input  wire s_axi_control_arvalid,
    output wire s_axi_control_arready,
    output wire [31:0] s_axi_control_rdata,
    output wire [1:0] s_axi_control_rresp,
    output wire s_axi_control_rvalid,
    input  wire s_axi_control_rready,

    input  wire [AXIL_AW-1:0] s_axi_loader_awaddr,
    input  wire s_axi_loader_awvalid,
    output wire s_axi_loader_awready,
    input  wire [31:0] s_axi_loader_wdata,
    input  wire [3:0] s_axi_loader_wstrb,
    input  wire s_axi_loader_wvalid,
    output wire s_axi_loader_wready,
    output wire [1:0] s_axi_loader_bresp,
    output wire s_axi_loader_bvalid,
    input  wire s_axi_loader_bready,
    input  wire [AXIL_AW-1:0] s_axi_loader_araddr,
    input  wire s_axi_loader_arvalid,
    output wire s_axi_loader_arready,
    output wire [31:0] s_axi_loader_rdata,
    output wire [1:0] s_axi_loader_rresp,
    output wire s_axi_loader_rvalid,
    input  wire s_axi_loader_rready,

    output wire [63:0] m_axi_gmem_araddr,
    output wire [7:0] m_axi_gmem_arlen,
    output wire [2:0] m_axi_gmem_arsize,
    output wire [1:0] m_axi_gmem_arburst,
    output wire m_axi_gmem_arvalid,
    input  wire m_axi_gmem_arready,
    input  wire [127:0] m_axi_gmem_rdata,
    input  wire [1:0] m_axi_gmem_rresp,
    input  wire m_axi_gmem_rlast,
    input  wire m_axi_gmem_rvalid,
    output wire m_axi_gmem_rready,
    output wire [63:0] m_axi_gmem_awaddr,
    output wire [7:0] m_axi_gmem_awlen,
    output wire [2:0] m_axi_gmem_awsize,
    output wire [1:0] m_axi_gmem_awburst,
    output wire m_axi_gmem_awvalid,
    input  wire m_axi_gmem_awready,
    output wire [127:0] m_axi_gmem_wdata,
    output wire [15:0] m_axi_gmem_wstrb,
    output wire m_axi_gmem_wlast,
    output wire m_axi_gmem_wvalid,
    input  wire m_axi_gmem_wready,
    input  wire [1:0] m_axi_gmem_bresp,
    input  wire m_axi_gmem_bvalid,
    output wire m_axi_gmem_bready,

    output wire interrupt
);
    localparam [7:0] BOARD_PREDICATES = 8'h11;

    m13_compute_lifecycle_integration #(
        .AXIL_AW(AXIL_AW), .TAG_W(TAG_W), .TRACE_ENABLE(0)
    ) u_compute (
        .clk(ap_clk), .rst_n(ap_rst_n),
        .s_axi_awaddr(s_axi_control_awaddr),
        .s_axi_awvalid(s_axi_control_awvalid),
        .s_axi_awready(s_axi_control_awready),
        .s_axi_wdata(s_axi_control_wdata),
        .s_axi_wstrb(s_axi_control_wstrb),
        .s_axi_wvalid(s_axi_control_wvalid),
        .s_axi_wready(s_axi_control_wready),
        .s_axi_bresp(s_axi_control_bresp),
        .s_axi_bvalid(s_axi_control_bvalid),
        .s_axi_bready(s_axi_control_bready),
        .s_axi_araddr(s_axi_control_araddr),
        .s_axi_arvalid(s_axi_control_arvalid),
        .s_axi_arready(s_axi_control_arready),
        .s_axi_rdata(s_axi_control_rdata),
        .s_axi_rresp(s_axi_control_rresp),
        .s_axi_rvalid(s_axi_control_rvalid),
        .s_axi_rready(s_axi_control_rready),
        .irq(interrupt),
        .s_loader_axi_awaddr(s_axi_loader_awaddr),
        .s_loader_axi_awvalid(s_axi_loader_awvalid),
        .s_loader_axi_awready(s_axi_loader_awready),
        .s_loader_axi_wdata(s_axi_loader_wdata),
        .s_loader_axi_wstrb(s_axi_loader_wstrb),
        .s_loader_axi_wvalid(s_axi_loader_wvalid),
        .s_loader_axi_wready(s_axi_loader_wready),
        .s_loader_axi_bresp(s_axi_loader_bresp),
        .s_loader_axi_bvalid(s_axi_loader_bvalid),
        .s_loader_axi_bready(s_axi_loader_bready),
        .s_loader_axi_araddr(s_axi_loader_araddr),
        .s_loader_axi_arvalid(s_axi_loader_arvalid),
        .s_loader_axi_arready(s_axi_loader_arready),
        .s_loader_axi_rdata(s_axi_loader_rdata),
        .s_loader_axi_rresp(s_axi_loader_rresp),
        .s_loader_axi_rvalid(s_axi_loader_rvalid),
        .s_loader_axi_rready(s_axi_loader_rready),
        .predicate_values(BOARD_PREDICATES),
        .compute_dma_done(1'b0),
        .aux_req_valid(2'b00), .aux_req_ready(),
        .aux_req_write(2'b00), .aux_req_addr(128'd0),
        .aux_req_bytes(32'd0), .aux_req_tag({2*TAG_W{1'b0}}),
        .aux_wr_valid(2'b00), .aux_wr_ready(),
        .aux_wr_data(256'd0), .aux_wr_keep(32'd0), .aux_wr_last(2'b00),
        .aux_rd_valid(), .aux_rd_ready(2'b11), .aux_rd_data(),
        .aux_rd_last(), .aux_rd_resp(), .aux_rd_tag(),
        .aux_done_valid(), .aux_done_ready(2'b11), .aux_done_tag(),
        .aux_done_error(), .aux_done_resp(), .aux_done_beat(),
        .m_axi_araddr(m_axi_gmem_araddr),
        .m_axi_arlen(m_axi_gmem_arlen), .m_axi_arsize(m_axi_gmem_arsize),
        .m_axi_arburst(m_axi_gmem_arburst),
        .m_axi_arvalid(m_axi_gmem_arvalid),
        .m_axi_arready(m_axi_gmem_arready),
        .m_axi_rdata(m_axi_gmem_rdata), .m_axi_rresp(m_axi_gmem_rresp),
        .m_axi_rlast(m_axi_gmem_rlast), .m_axi_rvalid(m_axi_gmem_rvalid),
        .m_axi_rready(m_axi_gmem_rready),
        .m_axi_awaddr(m_axi_gmem_awaddr),
        .m_axi_awlen(m_axi_gmem_awlen), .m_axi_awsize(m_axi_gmem_awsize),
        .m_axi_awburst(m_axi_gmem_awburst),
        .m_axi_awvalid(m_axi_gmem_awvalid),
        .m_axi_awready(m_axi_gmem_awready),
        .m_axi_wdata(m_axi_gmem_wdata), .m_axi_wstrb(m_axi_gmem_wstrb),
        .m_axi_wlast(m_axi_gmem_wlast), .m_axi_wvalid(m_axi_gmem_wvalid),
        .m_axi_wready(m_axi_gmem_wready),
        .m_axi_bresp(m_axi_gmem_bresp), .m_axi_bvalid(m_axi_gmem_bvalid),
        .m_axi_bready(m_axi_gmem_bready),
        .engine_busy(), .phase_active(), .execution_active(),
        .writeback_active(), .lifecycle_state(), .active_image_ok(),
        .active_context_count(), .operator_fault(), .operator_fault_detail(),
        .profile_total_cycles(), .profile_phase_cycles(),
        .profile_execution_cycles(), .profile_array_commit_cycles(),
        .profile_array_stall_cycles(), .profile_useful_pe_cycles(),
        .profile_useful_pe_slots(), .profile_resource_stall_cycles(),
        .profile_phi_generate_requests(), .profile_phi_replay_requests(),
        .profile_phi_replay_responses(), .profile_phi_cache_fills(),
        .profile_phi_output_symbols(), .profile_selection_accepts(),
        .profile_dma_read_requests(), .profile_dma_read_beats(),
        .profile_dma_write_requests(), .profile_dma_write_beats(),
        .profile_dma_write_responses(), .profile_result_drain_cycles(),
        .profile_result_drain_beats(),
        .final_support_count(), .final_support_indices(),
        .final_support_coefficients()
    );
endmodule

`default_nettype wire
