`ifndef CSR_HOST_REGISTERS_VH
`define CSR_HOST_REGISTERS_VH

`define CSR_HOST_AXI_ADDR_W 12
`define CSR_HOST_AXI_DATA_W 32
`define CSR_HOST_AXI_BYTES 4
`define CSR_HOST_MAP_BYTES 4096
`define CSR_HOST_VERSION 32'h0001_0000

`define CSR_HOST_REG_ID 12'h000
`define CSR_HOST_REG_STATUS 12'h004
`define CSR_HOST_REG_IRQ 12'h008
`define CSR_HOST_REG_ACK 12'h00c
`define CSR_HOST_REG_COMMAND 12'h010
`define CSR_HOST_REG_ERROR 12'h014
`define CSR_HOST_REG_EVENT 12'h018

`define CSR_HOST_REG_START_ROWS 12'h020
`define CSR_HOST_REG_START_COLS 12'h024
`define CSR_HOST_REG_START_SCALE 12'h028
`define CSR_HOST_REG_START_GENERATION 12'h02c
`define CSR_HOST_REG_START_JOB_TAG 12'h030
`define CSR_HOST_REG_START_KEY0 12'h034
`define CSR_HOST_REG_START_KEY1 12'h038
`define CSR_HOST_REG_START_KEY2 12'h03c
`define CSR_HOST_REG_START_KEY3 12'h040
`define CSR_HOST_REG_START_FORMAT 12'h044
`define CSR_HOST_REG_START_STORAGE 12'h048
`define CSR_HOST_REG_START_LIMIT 12'h04c

`define CSR_HOST_REG_LOAD_PROGRAM_COUNT 12'h050
`define CSR_HOST_REG_LOAD_CONSTANT_COUNT 12'h054
`define CSR_HOST_REG_LOAD_CONTROL 12'h058
`define CSR_HOST_REG_LOAD_ITEM_CONTROL 12'h05c
`define CSR_HOST_REG_LOAD_ITEM0 12'h060
`define CSR_HOST_REG_LOAD_ITEM1 12'h064
`define CSR_HOST_REG_LOAD_ITEM2 12'h068
`define CSR_HOST_REG_LOAD_ITEM3 12'h06c

`define CSR_HOST_REG_PHI_SEED 12'h070
`define CSR_HOST_REG_PHI_SHAPE 12'h074
`define CSR_HOST_REG_PHI_KEY0 12'h078
`define CSR_HOST_REG_PHI_KEY1 12'h07c
`define CSR_HOST_REG_PHI_KEY2 12'h080
`define CSR_HOST_REG_PHI_KEY3 12'h084
`define CSR_HOST_REG_PHI_GENERATION 12'h088
`define CSR_HOST_REG_PHI_JOB_TAG 12'h08c
`define CSR_HOST_REG_PHI_FORMAT 12'h090

`define CSR_HOST_REG_HOST_CONTROL 12'h0a0
`define CSR_HOST_REG_HOST_MASK 12'h0a4
`define CSR_HOST_REG_HOST_TAG 12'h0a8
`define CSR_HOST_REG_HOST_DATA0 12'h0ac
`define CSR_HOST_REG_HOST_DATA_LAST 12'h128

`define CSR_HOST_REG_RESULT_CONTROL 12'h140
`define CSR_HOST_REG_RESULT_DATA 12'h148
`define CSR_HOST_REG_RESULT_ID 12'h14c
`define CSR_HOST_REG_RESULT_META 12'h150
`define CSR_HOST_REG_RESULT_JOB_TAG 12'h154
`define CSR_HOST_REG_RESULT_FORMAT 12'h158
`define CSR_HOST_REG_RESULT_STATE 12'h15c

`define CSR_HOST_REG_HOST_RESPONSE_CONTROL 12'h160
`define CSR_HOST_REG_HOST_RESPONSE_MASK 12'h164
`define CSR_HOST_REG_HOST_RESPONSE_TAG_FAULT 12'h168
`define CSR_HOST_REG_HOST_RESPONSE_DATA0 12'h16c
`define CSR_HOST_REG_HOST_RESPONSE_DATA_LAST 12'h1e8

`define CSR_HOST_REG_DONE_STATUS 12'h200
`define CSR_HOST_REG_DONE_ITERATIONS 12'h204
`define CSR_HOST_REG_DONE_SUPPORT 12'h208
`define CSR_HOST_REG_DONE_TAG 12'h20c
`define CSR_HOST_REG_DONE_CYCLES_LO 12'h210
`define CSR_HOST_REG_DONE_CYCLES_HI 12'h214

`define CSR_HOST_REG_COMMITTED_META 12'h220
`define CSR_HOST_REG_COMMITTED_LENGTH 12'h224
`define CSR_HOST_REG_COMMITTED_ITERATIONS 12'h228
`define CSR_HOST_REG_COMMITTED_JOB_TAG 12'h22c
`define CSR_HOST_REG_COMMITTED_FORMAT 12'h230
`define CSR_HOST_REG_COMMITTED_KEY0 12'h234
`define CSR_HOST_REG_COMMITTED_KEY1 12'h238
`define CSR_HOST_REG_COMMITTED_KEY2 12'h23c
`define CSR_HOST_REG_COMMITTED_KEY3 12'h240
`define CSR_HOST_REG_COMMITTED_GENERATION 12'h244
`define CSR_HOST_REG_COMMITTED_SUPPORT0 12'h248
`define CSR_HOST_REG_COMMITTED_SUPPORT_LAST 12'h2bc

`define CSR_HOST_REG_IMAGE_STATUS 12'h2c0
`define CSR_HOST_REG_PHI_STATUS 12'h2c4
`define CSR_HOST_REG_PHI_IDENTITY 12'h2c8
`define CSR_HOST_REG_PHI_GENERATION_READ 12'h2cc
`define CSR_HOST_REG_PHI_SEED_READ 12'h2d0
`define CSR_HOST_REG_PHI_EPOCH 12'h2d4
`define CSR_HOST_REG_COMMAND_STATE 12'h2d8

`define CSR_HOST_COMMAND_START 8'h01
`define CSR_HOST_COMMAND_CANCEL 8'h02
`define CSR_HOST_COMMAND_LOAD_BEGIN 8'h04
`define CSR_HOST_COMMAND_LOAD_ITEM 8'h08
`define CSR_HOST_COMMAND_PHI_BEGIN 8'h10
`define CSR_HOST_COMMAND_HOST_READ 8'h20
`define CSR_HOST_COMMAND_HOST_WRITE 8'h40
`define CSR_HOST_COMMAND_RESULT_READ 8'h80
`define CSR_HOST_COMMAND_DEFINED_MASK 8'hff
`define CSR_HOST_COMMAND_RESERVED_MASK 32'hffff_ff00

`define CSR_HOST_OP_START 4'd0
`define CSR_HOST_OP_LOAD_BEGIN 4'd1
`define CSR_HOST_OP_LOAD_ITEM 4'd2
`define CSR_HOST_OP_PHI_BEGIN 4'd3
`define CSR_HOST_OP_HOST_READ 4'd4
`define CSR_HOST_OP_HOST_WRITE 4'd5
`define CSR_HOST_OP_RESULT_READ 4'd6

`define CSR_HOST_ACK_DONE 8'h01
`define CSR_HOST_ACK_RESULT 8'h02
`define CSR_HOST_ACK_HOST 8'h04
`define CSR_HOST_ACK_LOAD 8'h08
`define CSR_HOST_ACK_ERROR 8'h10
`define CSR_HOST_ACK_IRQ 8'h20
`define CSR_HOST_ACK_DEFINED_MASK 8'h3f
`define CSR_HOST_ACK_RESERVED_MASK 32'hffff_ffc0
`define CSR_HOST_IRQ_WRITABLE_MASK 32'h0000_0001
`define CSR_HOST_IRQ_RESERVED_MASK 32'hffff_fffe

`define CSR_HOST_STATUS_BUSY 32'h0000_0001
`define CSR_HOST_STATUS_IMAGE_VALID 32'h0000_0002
`define CSR_HOST_STATUS_IMAGE_LOADING 32'h0000_0004
`define CSR_HOST_STATUS_PHI_VALID 32'h0000_0008
`define CSR_HOST_STATUS_PHI_LOADING 32'h0000_0010
`define CSR_HOST_STATUS_COMMAND_PENDING 32'h0000_0020
`define CSR_HOST_STATUS_MAILBOX_VALID 32'h0000_0040
`define CSR_HOST_STATUS_DONE_VALID 32'h0000_0080
`define CSR_HOST_STATUS_HOST_RESPONSE 32'h0000_0100
`define CSR_HOST_STATUS_RESULT_RESPONSE 32'h0000_0200
`define CSR_HOST_STATUS_LOAD_STATUS 32'h0000_0400
`define CSR_HOST_STATUS_COMMAND_READY 32'h0000_0800
`define CSR_HOST_STATUS_COMMITTED_VALID 32'h0000_1000
`define CSR_HOST_STATUS_CANCEL_SEEN 32'h0000_2000
`define CSR_HOST_STATUS_ERROR_VALID 32'h0000_4000
`define CSR_HOST_STATUS_AXI_READY 32'h0000_8000

`define CSR_HOST_EVENT_NONE 4'd0
`define CSR_HOST_EVENT_START 4'd1
`define CSR_HOST_EVENT_LOAD_BEGIN 4'd2
`define CSR_HOST_EVENT_LOAD_ITEM 4'd3
`define CSR_HOST_EVENT_PHI_BEGIN 4'd4
`define CSR_HOST_EVENT_HOST_READ 4'd5
`define CSR_HOST_EVENT_HOST_WRITE 4'd6
`define CSR_HOST_EVENT_RESULT_READ 4'd7
`define CSR_HOST_EVENT_CANCEL 4'd8
`define CSR_HOST_EVENT_DONE 4'd9
`define CSR_HOST_EVENT_RESULT_RESPONSE 4'd10
`define CSR_HOST_EVENT_HOST_RESPONSE 4'd11
`define CSR_HOST_EVENT_LOAD_STATUS 4'd12

`define CSR_HOST_ERROR_NONE 4'd0
`define CSR_HOST_ERROR_BAD_ADDRESS 4'd1
`define CSR_HOST_ERROR_BAD_ALIGNMENT 4'd2
`define CSR_HOST_ERROR_READ_ONLY 4'd3
`define CSR_HOST_ERROR_BUSY 4'd4
`define CSR_HOST_ERROR_COMMAND 4'd5
`define CSR_HOST_ERROR_STROBE 4'd6

`define CSR_HOST_LOAD_REVISION_LSB 0
`define CSR_HOST_LOAD_REVISION_W 8
`define CSR_HOST_LOAD_TEMPLATE_LSB 8
`define CSR_HOST_LOAD_TEMPLATE_W 5
`define CSR_HOST_LOAD_VECTOR_LSB 13
`define CSR_HOST_LOAD_VECTOR_W 6
`define CSR_HOST_LOAD_VERIFIED_LSB 19
`define CSR_HOST_LOAD_ITEM_KIND_LSB 0
`define CSR_HOST_LOAD_ITEM_KIND_W 3
`define CSR_HOST_LOAD_ITEM_INDEX_LSB 3
`define CSR_HOST_LOAD_ITEM_INDEX_W 16
`define CSR_HOST_LOAD_ITEM_LAST_LSB 19

`define CSR_HOST_STATUS_DONE_VALID_LSB 17
`define CSR_HOST_STATUS_DONE_VALID_W 1
`define CSR_HOST_STATUS_DONE_COMMITTED_LSB 16
`define CSR_HOST_STATUS_DONE_COMMITTED_W 1

`define CSR_HOST_START_STORAGE_LSB 0
`define CSR_HOST_START_STORAGE_W 2
`define CSR_HOST_START_EXPONENT_LSB 8
`define CSR_HOST_START_EXPONENT_W 7
`define CSR_HOST_START_ACTIVE_SUPPORT_LSB 16

`define CSR_HOST_COMMITTED_VALID_LSB 0
`define CSR_HOST_COMMITTED_ACTIVE_SUPPORT_LSB 1
`define CSR_HOST_COMMITTED_ROWS_LSB 2
`define CSR_HOST_COMMITTED_MODE_LSB 10
`define CSR_HOST_COMMITTED_EXPONENT_LSB 12
`define CSR_HOST_COMMITTED_STATUS_LSB 19

`define CSR_HOST_PHI_ROWS_LSB 0
`define CSR_HOST_PHI_ROWS_W 8
`define CSR_HOST_PHI_COLS_LSB 16
`define CSR_HOST_PHI_COLS_W 11

`endif
