`ifndef CSR_SCALAR_INTERFACE_VH
`define CSR_SCALAR_INTERFACE_VH
`define CSR_SCALAR_N_W 64
`define CSR_SCALAR_S_W 27
`define CSR_SCALAR_S_F 22
`define CSR_SCALAR_JOB_W 16
`define CSR_SCALAR_TAG_W 16
`define CSR_SCALAR_FMT_W 8
`define CSR_SCALAR_OP_W 2
`define CSR_SCALAR_FAULT_W 3
`define CSR_SCALAR_FRAC_W 8
`define CSR_SCALAR_FORMAT 1
`define CSR_SCALAR_DIV_FRAC 0
`define CSR_SCALAR_SQRT_FRAC 44
`define CSR_SCALAR_OP_DIV 0
`define CSR_SCALAR_OP_SQRT 1
`define CSR_SCALAR_FAULT_NONE 0
`define CSR_SCALAR_FAULT_MODE 1
`define CSR_SCALAR_FAULT_ZERO 2
`define CSR_SCALAR_FAULT_NEGATIVE 3
`define CSR_SCALAR_FAULT_RANGE 4
`define CSR_SCALAR_SCHEDULE_DIV_LATENCY 87
`define CSR_SCALAR_SCHEDULE_SQRT_LATENCY 33
`define CSR_SCALAR_SCHEDULE_FAULT_LATENCY 1
`define CSR_SCALAR_SCHEDULE_DIV_II 89
`define CSR_SCALAR_SCHEDULE_SQRT_II 35
`define CSR_SCALAR_SCHEDULE_FAULT_II 3
`endif
