module tb_cgra_fabric;
reg clk = 0;
wire [31:0] rsp_halt;
reg [3568:0] stim;
wire req_operands;
wire [31:0] req_enable;
wire [0:0] rst;
wire [0:0] cancel;
wire [0:0] req_valid;
wire [1:0] req_mode;
wire [0:0] req_trans;
wire [7:0] req_rows;
wire [10:0] req_cols;
wire [10:0] req_out;
wire [10:0] req_red;
wire [2:0] req_step;
wire [17:0] req_scale;
wire [255:0] req_signs;
wire [255:0] req_masks;
wire [7:0] req_sign_valid;
wire [575:0] req_dense;
wire [31:0] req_dense_valid;
wire [107:0] req_vec;
wire [3:0] req_vec_valid;
wire [0:0] req_src_fault;
wire [15:0] req_job;
wire [15:0] req_tag;
wire [7:0] req_fmt;
wire [0:0] req_last;
wire [0:0] rsp_ready;
wire [2047:0] req_words;
wire [7:0] req_rev;
wire [0:0] req_alu_mode;
wire [127:0] link_ready;
wire [0:0] req_ready;
wire [0:0] rsp_valid;
wire [863:0] rsp_data;
wire [2047:0] rsp_acc;
wire [127:0] rsp_faults;
wire [31:0] rsp_store;
wire [31:0] rsp_exec;
wire [0:0] rsp_fault;
wire [3:0] rsp_feed_fault;
wire [15:0] rsp_job;
wire [15:0] rsp_tag;
wire [7:0] rsp_fmt;
wire [0:0] rsp_last;
wire [2047:0] state_acc;
wire [6911:0] state_rf;
wire [255:0] state_valid;
wire [95:0] state_preds;
assign {rst, cancel, req_valid, req_mode, req_trans, req_rows, req_cols, req_out, req_red, req_step, req_scale, req_signs, req_masks, req_sign_valid, req_dense, req_dense_valid, req_vec, req_vec_valid, req_src_fault, req_job, req_tag, req_fmt, req_last, rsp_ready, req_words, req_rev, req_alu_mode, link_ready, req_operands, req_enable} = stim;
cgra_fabric dut (.clk(clk), .rsp_halt(rsp_halt), .req_operands(req_operands), .req_enable(req_enable), .rst(rst), .cancel(cancel), .req_valid(req_valid), .req_mode(req_mode), .req_trans(req_trans), .req_rows(req_rows), .req_cols(req_cols), .req_out(req_out), .req_red(req_red), .req_step(req_step), .req_scale(req_scale), .req_signs(req_signs), .req_masks(req_masks), .req_sign_valid(req_sign_valid), .req_dense(req_dense), .req_dense_valid(req_dense_valid), .req_vec(req_vec), .req_vec_valid(req_vec_valid), .req_src_fault(req_src_fault), .req_job(req_job), .req_tag(req_tag), .req_fmt(req_fmt), .req_last(req_last), .rsp_ready(rsp_ready), .req_words(req_words), .req_rev(req_rev), .req_alu_mode(req_alu_mode), .link_ready(link_ready), .req_ready(req_ready), .rsp_valid(rsp_valid), .rsp_data(rsp_data), .rsp_acc(rsp_acc), .rsp_faults(rsp_faults), .rsp_store(rsp_store), .rsp_exec(rsp_exec), .rsp_fault(rsp_fault), .rsp_feed_fault(rsp_feed_fault), .rsp_job(rsp_job), .rsp_tag(rsp_tag), .rsp_fmt(rsp_fmt), .rsp_last(rsp_last));
assign state_acc[0 +: 64] = dut.array_pair[0].array_core.pe[0].ctx.tile.acc_view;
assign state_rf[0 +: 216] = dut.array_pair[0].array_core.pe[0].ctx.tile.rf_flat;
assign state_valid[0 +: 8] = dut.array_pair[0].array_core.pe[0].ctx.tile.rf_valid;
assign state_preds[0 +: 3] = dut.array_pair[0].array_core.pe[0].ctx.tile.preds;
assign state_acc[64 +: 64] = dut.array_pair[0].array_core.pe[1].ctx.tile.acc_view;
assign state_rf[216 +: 216] = dut.array_pair[0].array_core.pe[1].ctx.tile.rf_flat;
assign state_valid[8 +: 8] = dut.array_pair[0].array_core.pe[1].ctx.tile.rf_valid;
assign state_preds[3 +: 3] = dut.array_pair[0].array_core.pe[1].ctx.tile.preds;
assign state_acc[128 +: 64] = dut.array_pair[0].array_core.pe[2].ctx.tile.acc_view;
assign state_rf[432 +: 216] = dut.array_pair[0].array_core.pe[2].ctx.tile.rf_flat;
assign state_valid[16 +: 8] = dut.array_pair[0].array_core.pe[2].ctx.tile.rf_valid;
assign state_preds[6 +: 3] = dut.array_pair[0].array_core.pe[2].ctx.tile.preds;
assign state_acc[192 +: 64] = dut.array_pair[0].array_core.pe[3].ctx.tile.acc_view;
assign state_rf[648 +: 216] = dut.array_pair[0].array_core.pe[3].ctx.tile.rf_flat;
assign state_valid[24 +: 8] = dut.array_pair[0].array_core.pe[3].ctx.tile.rf_valid;
assign state_preds[9 +: 3] = dut.array_pair[0].array_core.pe[3].ctx.tile.preds;
assign state_acc[256 +: 64] = dut.array_pair[0].array_core.pe[4].ctx.tile.acc_view;
assign state_rf[864 +: 216] = dut.array_pair[0].array_core.pe[4].ctx.tile.rf_flat;
assign state_valid[32 +: 8] = dut.array_pair[0].array_core.pe[4].ctx.tile.rf_valid;
assign state_preds[12 +: 3] = dut.array_pair[0].array_core.pe[4].ctx.tile.preds;
assign state_acc[320 +: 64] = dut.array_pair[0].array_core.pe[5].ctx.tile.acc_view;
assign state_rf[1080 +: 216] = dut.array_pair[0].array_core.pe[5].ctx.tile.rf_flat;
assign state_valid[40 +: 8] = dut.array_pair[0].array_core.pe[5].ctx.tile.rf_valid;
assign state_preds[15 +: 3] = dut.array_pair[0].array_core.pe[5].ctx.tile.preds;
assign state_acc[384 +: 64] = dut.array_pair[0].array_core.pe[6].ctx.tile.acc_view;
assign state_rf[1296 +: 216] = dut.array_pair[0].array_core.pe[6].ctx.tile.rf_flat;
assign state_valid[48 +: 8] = dut.array_pair[0].array_core.pe[6].ctx.tile.rf_valid;
assign state_preds[18 +: 3] = dut.array_pair[0].array_core.pe[6].ctx.tile.preds;
assign state_acc[448 +: 64] = dut.array_pair[0].array_core.pe[7].ctx.tile.acc_view;
assign state_rf[1512 +: 216] = dut.array_pair[0].array_core.pe[7].ctx.tile.rf_flat;
assign state_valid[56 +: 8] = dut.array_pair[0].array_core.pe[7].ctx.tile.rf_valid;
assign state_preds[21 +: 3] = dut.array_pair[0].array_core.pe[7].ctx.tile.preds;
assign state_acc[512 +: 64] = dut.array_pair[0].array_core.pe[8].ctx.tile.acc_view;
assign state_rf[1728 +: 216] = dut.array_pair[0].array_core.pe[8].ctx.tile.rf_flat;
assign state_valid[64 +: 8] = dut.array_pair[0].array_core.pe[8].ctx.tile.rf_valid;
assign state_preds[24 +: 3] = dut.array_pair[0].array_core.pe[8].ctx.tile.preds;
assign state_acc[576 +: 64] = dut.array_pair[0].array_core.pe[9].ctx.tile.acc_view;
assign state_rf[1944 +: 216] = dut.array_pair[0].array_core.pe[9].ctx.tile.rf_flat;
assign state_valid[72 +: 8] = dut.array_pair[0].array_core.pe[9].ctx.tile.rf_valid;
assign state_preds[27 +: 3] = dut.array_pair[0].array_core.pe[9].ctx.tile.preds;
assign state_acc[640 +: 64] = dut.array_pair[0].array_core.pe[10].ctx.tile.acc_view;
assign state_rf[2160 +: 216] = dut.array_pair[0].array_core.pe[10].ctx.tile.rf_flat;
assign state_valid[80 +: 8] = dut.array_pair[0].array_core.pe[10].ctx.tile.rf_valid;
assign state_preds[30 +: 3] = dut.array_pair[0].array_core.pe[10].ctx.tile.preds;
assign state_acc[704 +: 64] = dut.array_pair[0].array_core.pe[11].ctx.tile.acc_view;
assign state_rf[2376 +: 216] = dut.array_pair[0].array_core.pe[11].ctx.tile.rf_flat;
assign state_valid[88 +: 8] = dut.array_pair[0].array_core.pe[11].ctx.tile.rf_valid;
assign state_preds[33 +: 3] = dut.array_pair[0].array_core.pe[11].ctx.tile.preds;
assign state_acc[768 +: 64] = dut.array_pair[0].array_core.pe[12].ctx.tile.acc_view;
assign state_rf[2592 +: 216] = dut.array_pair[0].array_core.pe[12].ctx.tile.rf_flat;
assign state_valid[96 +: 8] = dut.array_pair[0].array_core.pe[12].ctx.tile.rf_valid;
assign state_preds[36 +: 3] = dut.array_pair[0].array_core.pe[12].ctx.tile.preds;
assign state_acc[832 +: 64] = dut.array_pair[0].array_core.pe[13].ctx.tile.acc_view;
assign state_rf[2808 +: 216] = dut.array_pair[0].array_core.pe[13].ctx.tile.rf_flat;
assign state_valid[104 +: 8] = dut.array_pair[0].array_core.pe[13].ctx.tile.rf_valid;
assign state_preds[39 +: 3] = dut.array_pair[0].array_core.pe[13].ctx.tile.preds;
assign state_acc[896 +: 64] = dut.array_pair[0].array_core.pe[14].ctx.tile.acc_view;
assign state_rf[3024 +: 216] = dut.array_pair[0].array_core.pe[14].ctx.tile.rf_flat;
assign state_valid[112 +: 8] = dut.array_pair[0].array_core.pe[14].ctx.tile.rf_valid;
assign state_preds[42 +: 3] = dut.array_pair[0].array_core.pe[14].ctx.tile.preds;
assign state_acc[960 +: 64] = dut.array_pair[0].array_core.pe[15].ctx.tile.acc_view;
assign state_rf[3240 +: 216] = dut.array_pair[0].array_core.pe[15].ctx.tile.rf_flat;
assign state_valid[120 +: 8] = dut.array_pair[0].array_core.pe[15].ctx.tile.rf_valid;
assign state_preds[45 +: 3] = dut.array_pair[0].array_core.pe[15].ctx.tile.preds;
assign state_acc[1024 +: 64] = dut.array_pair[1].array_core.pe[0].ctx.tile.acc_view;
assign state_rf[3456 +: 216] = dut.array_pair[1].array_core.pe[0].ctx.tile.rf_flat;
assign state_valid[128 +: 8] = dut.array_pair[1].array_core.pe[0].ctx.tile.rf_valid;
assign state_preds[48 +: 3] = dut.array_pair[1].array_core.pe[0].ctx.tile.preds;
assign state_acc[1088 +: 64] = dut.array_pair[1].array_core.pe[1].ctx.tile.acc_view;
assign state_rf[3672 +: 216] = dut.array_pair[1].array_core.pe[1].ctx.tile.rf_flat;
assign state_valid[136 +: 8] = dut.array_pair[1].array_core.pe[1].ctx.tile.rf_valid;
assign state_preds[51 +: 3] = dut.array_pair[1].array_core.pe[1].ctx.tile.preds;
assign state_acc[1152 +: 64] = dut.array_pair[1].array_core.pe[2].ctx.tile.acc_view;
assign state_rf[3888 +: 216] = dut.array_pair[1].array_core.pe[2].ctx.tile.rf_flat;
assign state_valid[144 +: 8] = dut.array_pair[1].array_core.pe[2].ctx.tile.rf_valid;
assign state_preds[54 +: 3] = dut.array_pair[1].array_core.pe[2].ctx.tile.preds;
assign state_acc[1216 +: 64] = dut.array_pair[1].array_core.pe[3].ctx.tile.acc_view;
assign state_rf[4104 +: 216] = dut.array_pair[1].array_core.pe[3].ctx.tile.rf_flat;
assign state_valid[152 +: 8] = dut.array_pair[1].array_core.pe[3].ctx.tile.rf_valid;
assign state_preds[57 +: 3] = dut.array_pair[1].array_core.pe[3].ctx.tile.preds;
assign state_acc[1280 +: 64] = dut.array_pair[1].array_core.pe[4].ctx.tile.acc_view;
assign state_rf[4320 +: 216] = dut.array_pair[1].array_core.pe[4].ctx.tile.rf_flat;
assign state_valid[160 +: 8] = dut.array_pair[1].array_core.pe[4].ctx.tile.rf_valid;
assign state_preds[60 +: 3] = dut.array_pair[1].array_core.pe[4].ctx.tile.preds;
assign state_acc[1344 +: 64] = dut.array_pair[1].array_core.pe[5].ctx.tile.acc_view;
assign state_rf[4536 +: 216] = dut.array_pair[1].array_core.pe[5].ctx.tile.rf_flat;
assign state_valid[168 +: 8] = dut.array_pair[1].array_core.pe[5].ctx.tile.rf_valid;
assign state_preds[63 +: 3] = dut.array_pair[1].array_core.pe[5].ctx.tile.preds;
assign state_acc[1408 +: 64] = dut.array_pair[1].array_core.pe[6].ctx.tile.acc_view;
assign state_rf[4752 +: 216] = dut.array_pair[1].array_core.pe[6].ctx.tile.rf_flat;
assign state_valid[176 +: 8] = dut.array_pair[1].array_core.pe[6].ctx.tile.rf_valid;
assign state_preds[66 +: 3] = dut.array_pair[1].array_core.pe[6].ctx.tile.preds;
assign state_acc[1472 +: 64] = dut.array_pair[1].array_core.pe[7].ctx.tile.acc_view;
assign state_rf[4968 +: 216] = dut.array_pair[1].array_core.pe[7].ctx.tile.rf_flat;
assign state_valid[184 +: 8] = dut.array_pair[1].array_core.pe[7].ctx.tile.rf_valid;
assign state_preds[69 +: 3] = dut.array_pair[1].array_core.pe[7].ctx.tile.preds;
assign state_acc[1536 +: 64] = dut.array_pair[1].array_core.pe[8].ctx.tile.acc_view;
assign state_rf[5184 +: 216] = dut.array_pair[1].array_core.pe[8].ctx.tile.rf_flat;
assign state_valid[192 +: 8] = dut.array_pair[1].array_core.pe[8].ctx.tile.rf_valid;
assign state_preds[72 +: 3] = dut.array_pair[1].array_core.pe[8].ctx.tile.preds;
assign state_acc[1600 +: 64] = dut.array_pair[1].array_core.pe[9].ctx.tile.acc_view;
assign state_rf[5400 +: 216] = dut.array_pair[1].array_core.pe[9].ctx.tile.rf_flat;
assign state_valid[200 +: 8] = dut.array_pair[1].array_core.pe[9].ctx.tile.rf_valid;
assign state_preds[75 +: 3] = dut.array_pair[1].array_core.pe[9].ctx.tile.preds;
assign state_acc[1664 +: 64] = dut.array_pair[1].array_core.pe[10].ctx.tile.acc_view;
assign state_rf[5616 +: 216] = dut.array_pair[1].array_core.pe[10].ctx.tile.rf_flat;
assign state_valid[208 +: 8] = dut.array_pair[1].array_core.pe[10].ctx.tile.rf_valid;
assign state_preds[78 +: 3] = dut.array_pair[1].array_core.pe[10].ctx.tile.preds;
assign state_acc[1728 +: 64] = dut.array_pair[1].array_core.pe[11].ctx.tile.acc_view;
assign state_rf[5832 +: 216] = dut.array_pair[1].array_core.pe[11].ctx.tile.rf_flat;
assign state_valid[216 +: 8] = dut.array_pair[1].array_core.pe[11].ctx.tile.rf_valid;
assign state_preds[81 +: 3] = dut.array_pair[1].array_core.pe[11].ctx.tile.preds;
assign state_acc[1792 +: 64] = dut.array_pair[1].array_core.pe[12].ctx.tile.acc_view;
assign state_rf[6048 +: 216] = dut.array_pair[1].array_core.pe[12].ctx.tile.rf_flat;
assign state_valid[224 +: 8] = dut.array_pair[1].array_core.pe[12].ctx.tile.rf_valid;
assign state_preds[84 +: 3] = dut.array_pair[1].array_core.pe[12].ctx.tile.preds;
assign state_acc[1856 +: 64] = dut.array_pair[1].array_core.pe[13].ctx.tile.acc_view;
assign state_rf[6264 +: 216] = dut.array_pair[1].array_core.pe[13].ctx.tile.rf_flat;
assign state_valid[232 +: 8] = dut.array_pair[1].array_core.pe[13].ctx.tile.rf_valid;
assign state_preds[87 +: 3] = dut.array_pair[1].array_core.pe[13].ctx.tile.preds;
assign state_acc[1920 +: 64] = dut.array_pair[1].array_core.pe[14].ctx.tile.acc_view;
assign state_rf[6480 +: 216] = dut.array_pair[1].array_core.pe[14].ctx.tile.rf_flat;
assign state_valid[240 +: 8] = dut.array_pair[1].array_core.pe[14].ctx.tile.rf_valid;
assign state_preds[90 +: 3] = dut.array_pair[1].array_core.pe[14].ctx.tile.preds;
assign state_acc[1984 +: 64] = dut.array_pair[1].array_core.pe[15].ctx.tile.acc_view;
assign state_rf[6696 +: 216] = dut.array_pair[1].array_core.pe[15].ctx.tile.rf_flat;
assign state_valid[248 +: 8] = dut.array_pair[1].array_core.pe[15].ctx.tile.rf_valid;
assign state_preds[93 +: 3] = dut.array_pair[1].array_core.pe[15].ctx.tile.preds;
integer src, dst, count, cycle;
reg [4095:0] src_path, dst_path;
initial begin
if (!$value$plusargs("src=%s", src_path)) $fatal(1, "missing vectors");
if (!$value$plusargs("dst=%s", dst_path)) $fatal(1, "missing trace");
src = $fopen(src_path, "r"); dst = $fopen(dst_path, "w");
if (!src || !dst) $fatal(1, "cannot open files");
cycle = 0;
while (!$feof(src)) begin
count = $fscanf(src, "%h", stim);
if (count == 1) begin
#4;
$fdisplay(dst, "%0d 0 %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h", cycle, req_ready, rsp_valid, rsp_data, rsp_acc, rsp_faults, rsp_store, rsp_exec, rsp_fault, rsp_feed_fault, rsp_job, rsp_tag, rsp_fmt, rsp_last, state_acc, state_rf, state_valid, state_preds, rsp_halt);
clk = 1; #1;
$fdisplay(dst, "%0d 1 %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h", cycle, req_ready, rsp_valid, rsp_data, rsp_acc, rsp_faults, rsp_store, rsp_exec, rsp_fault, rsp_feed_fault, rsp_job, rsp_tag, rsp_fmt, rsp_last, state_acc, state_rf, state_valid, state_preds, rsp_halt);
#4; clk = 0; cycle = cycle + 1;
end else if (!$feof(src)) $fatal(1, "bad vector row");
end
$fclose(src); $fclose(dst);
$display("PASS cycles=%0d", cycle); $finish;
end
initial begin #10000000; $fatal(1, "timeout"); end
endmodule
