`ifndef CSR_RECOVERY_INTERFACE_VH
`define CSR_RECOVERY_INTERFACE_VH
`define CSR_RECOVERY_REVISION 1
`define CSR_RECOVERY_FAULT_NONE 0
`define CSR_RECOVERY_FAULT_START 1
`define CSR_RECOVERY_FAULT_PROGRAM 2
`define CSR_RECOVERY_FAULT_BUILD 3
`define CSR_RECOVERY_FAULT_READ 4
`define CSR_RECOVERY_FAULT_RESULT 5
`define CSR_RECOVERY_FAULT_IDENTITY 6
`define CSR_RECOVERY_FAULT_GENERATION 7
`define CSR_RECOVERY_RESULT_FAULT_NONE 0
`define CSR_RECOVERY_RESULT_FAULT_COMMAND 1
`define CSR_RECOVERY_RESULT_FAULT_RANGE 2
`define CSR_RECOVERY_RESULT_FAULT_ORDER 3
`define CSR_RECOVERY_RESULT_FAULT_EMBEDDING 4
`define CSR_RECOVERY_RESULT_FAULT_IDENTITY 5
`define CSR_RECOVERY_RESULT_FAULT_REJECTED 6
`define CSR_RECOVERY_RESULT_FAULT_UNINITIALIZED 7
`define CSR_RECOVERY_LIMIT_MAX_ROWS 128
`define CSR_RECOVERY_LIMIT_MAX_LENGTH 1024
`define CSR_RECOVERY_LIMIT_MAX_SUPPORT 96
`define CSR_RECOVERY_LIMIT_PUBLIC_BLOCKS 480
`define CSR_RECOVERY_LIMIT_FORMAT 1
`define CSR_RECOVERY_STORE_X24 1
`define CSR_RECOVERY_STORE_D18 2
`endif
