`ifndef CSR_TILE_INTERFACE_VH
`define CSR_TILE_INTERFACE_VH
`include "pe_interface.vh"
`define CSR_TILE_RF_WORDS 8
`define CSR_TILE_PRED_BITS 3
`define CSR_TILE_SRC_W 4
`define CSR_TILE_REG_W 3
`define CSR_TILE_GUARD_W 3
`define CSR_TILE_PDST_W 2
`define CSR_TILE_IMM_W 16
`define CSR_TILE_SRC_NONE 0
`define CSR_TILE_SRC_ACC 1
`define CSR_TILE_SRC_RF 2
`define CSR_TILE_SRC_MATRIX 3
`define CSR_TILE_SRC_VECTOR 4
`define CSR_TILE_SRC_IMMEDIATE 5
`define CSR_TILE_SRC_LINK 6
`define CSR_TILE_SRC_PREDICATE 7
`define CSR_TILE_GUARD_ALWAYS 0
`define CSR_TILE_GUARD_P0 1
`define CSR_TILE_GUARD_P1 2
`define CSR_TILE_GUARD_P2 3
`define CSR_TILE_GUARD_NOT_P0 4
`define CSR_TILE_GUARD_NOT_P1 5
`define CSR_TILE_GUARD_NOT_P2 6
`define CSR_TILE_GUARD_NEVER 7
`define CSR_TILE_PSEL_DATA 0
`define CSR_TILE_PSEL_LT 1
`define CSR_TILE_PSEL_EQ 2
`define CSR_TILE_PSEL_GT 3
`define CSR_TILE_PSEL_NOT_DATA 4
`define CSR_TILE_PSEL_ZERO 5
`define CSR_TILE_PSEL_ONE 6
`define CSR_TILE_FAULT_SOURCE 6
`define CSR_TILE_FAULT_UNINIT 7
`define CSR_TILE_FAULT_PRED 8
`define CSR_TILE_FAULT_LINK 9
`define CSR_TILE_FAULT_ACC_RANGE 10
`endif
