"""Static contract check for the active v2 Verilog TB and SoC C runner."""

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
TB = ROOT / "verification" / "v2" / "run1" / "tb_run1_k_sweep.v"
C = ROOT / "sw" / "v2" / "src" / "main_tb_soc_program_k_sweep_all_ls_serial_write.c"
H = ROOT / "sw" / "v2" / "src" / "cscgra_k_sweep_golden.h"


def read(path: Path) -> str:
    if not path.exists():
        raise SystemExit(f"missing file: {path}")
    return path.read_text(errors="replace")


tb, c, h = read(TB), read(C), read(H)
errors: list[str] = []

def require(condition: bool, message: str) -> None:
    if not condition:
        errors.append(message)


require('`include "k_sweep_golden_hardware.vh"' in tb, "TB does not include hardware golden")
require("hwgold_x_final" in tb and "hwgold_y" in tb, "TB does not consume hardware golden functions")
require("KSGOLD_SOURCE_TAG \"models/reference/hardware.py\"" in h, "C header is not generated by hardware.py")
require("#define KSGOLD_TOL 0U" in h, "C header is not bit-exact")
require("KSGOLD_SOURCE_TAG" in c, "C runner does not print its golden source tag")
require("requires_2K_candidate_support" in c and "requires_2K_candidate_support" in tb, "K16 skip rule is not mirrored")
require("run_rc == 2" in c, "C runner does not exclude intentional skips from failures")
require("KSGOLD_CASE_COUNT 8U" in h and "KSGOLD_ALG_COUNT 8U" in h, "C header dimensions are stale")

case_text = "m64n256k16, m64n256k8, m64n256k4, m32n128k8, m32n128k4, m32n128k2, m16n64k4, m16n64k2"
require(case_text in c, "C runner case list is stale")
for token in (
    "SOP_REFINE_SPARSE", "SOP_CORR_UPDATE", "SOP_PRUNE_X", "SOP_RESID",
    "SOP_MP_UPDATE", "SOP_GP_PROJECT", "SOP_GP_UPDATE",
):
    require(token in c, f"C runner missing {token}")
require(
    "case ALG_GP:" in c and "sparse_op_ctx(SOP_GP_PROJECT" in c
    and "sparse_op_ctx(SOP_GP_UPDATE" in c,
    "C runner GP is not the canonical-derived hardware program",
)
require(
    "ALG_5: begin" in tb and "sparse_op_ctx(SOP_GP_PROJECT" in tb
    and "sparse_op_ctx(SOP_GP_UPDATE" in tb,
    "TB GP is not the canonical-derived hardware program",
)

sv_alg = re.search(r"ALG_OMP=0, ALG_COSAMP=1, ALG_IHT=2, ALG_HTP=3, ALG_SP=4, ALG_5=5, ALG_6=6, ALG_MP=7", tb)
require(sv_alg is not None, "TB algorithm map changed")

if errors:
    print("SDK/TB sync FAIL")
    for error in errors:
        print(f"- {error}")
    sys.exit(1)
print("SDK/TB sync PASS: active hardware golden, context opcodes, case list, and skip rule agree")
