`ifndef CSR_FEEDER_INTERFACE_VH
`define CSR_FEEDER_INTERFACE_VH
`define CSR_FEED_MAX_ROWS 128
`define CSR_FEED_MAX_COLS 1024
`define CSR_FEED_MAX_SUPPORT 96
`define CSR_FEED_MODE_PHI_R1 0
`define CSR_FEED_MODE_PHI_R4 1
`define CSR_FEED_MODE_B_R1 2
`define CSR_FEED_MODE_B_R4 3
`define CSR_FEED_FAULT_NONE 0
`define CSR_FEED_FAULT_SHAPE 1
`define CSR_FEED_FAULT_INDEX 2
`define CSR_FEED_FAULT_SCALE 3
`define CSR_FEED_FAULT_SOURCE 4
`endif
