"""Generate the canonical, capacity-unlimited K-sweep golden include."""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

try:
    from .canonical_algorithms import run_all
    from . import canonical_fixed as fixed
except ImportError:  # direct ``python models/golden/*.py`` execution
    from canonical_algorithms import run_all
    import canonical_fixed as fixed


ROOT = Path(__file__).resolve().parents[2]
IMMUTABLE = ROOT / "models" / "golden" / "golden_cases.vh"
DEFAULT_OUT = ROOT / "verification" / "v2" / "run1" / "k_sweep_golden_canonical.vh"
Q = fixed.Q
MU_SHIFT = 3
CASES = [(64, 256, 16), (64, 256, 8), (64, 256, 4),
         (32, 128, 8), (32, 128, 4), (32, 128, 2),
         (16, 64, 4), (16, 64, 2)]
ALGORITHM_NAMES = ["OMP", "CoSaMP", "IHT", "HTP", "SP", "GP", "GOMP", "MP"]


def parse_hex_func(text: str, fname: str) -> dict[int, int]:
    match = re.search(rf"function\s+\[[^\]]+\]\s+{fname};(?P<body>.*?)endfunction", text, re.S)
    if not match:
        raise ValueError(f"missing {fname}")
    return {int(key): int(value, 16) for key, value in re.findall(
        rf"\b(\d+)\s*:\s*{fname}\s*=\s*\d+'h([0-9a-fA-F]+)\s*;", match.group("body"))}


def parse_int_func(text: str, fname: str) -> dict[int, int]:
    match = re.search(rf"function\s+integer\s+{fname};(?P<body>.*?)endfunction", text, re.S)
    if not match:
        raise ValueError(f"missing {fname}")
    return {int(key): int(value) for key, value in re.findall(
        rf"\b(\d+)\s*:\s*{fname}\s*=\s*(\d+)\s*;", match.group("body"))}


def quantize_float(value: float) -> int:
    magnitude = int(math.floor(abs(value) * (1 << Q) + 0.5))
    return fixed.sat_s24(-magnitude if value < 0 else magnitude)


def hex24(value: int) -> str:
    return f"24'h{value & fixed.DATA_MASK:06X}"


def emit_int_func(lines: list[str], name: str, values: list[int], default: int) -> None:
    lines.append(f"function integer {name};")
    lines.append("input integer case_idx; begin case(case_idx)")
    for idx, value in enumerate(values):
        lines.append(f"  {idx}: {name} = {value};")
    lines.append(f"  default: {name} = {default}; endcase end endfunction")


def _q24(values: list[float]) -> list[int]:
    return [quantize_float(value) for value in values]


def generate(output_path: Path) -> str:
    immutable = IMMUTABLE.read_text(errors="ignore")
    immutable_y = parse_hex_func(immutable, "gold_y")
    seed = parse_int_func(immutable, "gold_case_seed").get(0, 17)
    scale_q = parse_hex_func(immutable, "gold_case_scale").get(0, 0x4000)
    phi_kind = parse_hex_func(immutable, "gold_case_phi_kind").get(0, 0)
    y64_q = [fixed.s24(immutable_y.get(idx, 0)) for idx in range(64)]

    lines = [
        "// Auto-generated by models/golden/generate_canonical_k_sweep.py",
        "// Canonical references; no RTL merge-cap or PE scheduling limit.",
        "// IHT/HTP use step_size=1/8 to match the declared v2 numerical scale.",
        "// GP is generated by canonical_fixed.py (Q16/signed-24-bit contract).",
        "localparam integer KSCANON_GOLD_CASES = 8;",
        "localparam integer KSCANON_GOLD_ALGS = 8;",
        "localparam integer KSCANON_GOLD_MAX_N = 256;",
        "localparam integer KSCANON_GOLD_TOL = 512;",
    ]
    for case_idx, (m_size, n_size, k_size) in enumerate(CASES):
        lines.extend([
            f"localparam integer KSCANON_CASE_{case_idx}_M = {m_size};",
            f"localparam integer KSCANON_CASE_{case_idx}_N = {n_size};",
            f"localparam integer KSCANON_CASE_{case_idx}_K = {k_size};",
        ])

    emit_int_func(lines, "kscanon_case_m", [item[0] for item in CASES], 0)
    emit_int_func(lines, "kscanon_case_n", [item[1] for item in CASES], 0)
    emit_int_func(lines, "kscanon_case_k", [item[2] for item in CASES], 0)
    emit_int_func(lines, "kscanon_case_seed", [seed] * len(CASES), seed)
    lines.append("function [23:0] kscanon_case_scale;")
    lines.append("input integer case_idx; begin case(case_idx)")
    for case_idx in range(len(CASES)):
        lines.append(f"  {case_idx}: kscanon_case_scale = {hex24(scale_q)};")
    lines.append(f"  default: kscanon_case_scale = {hex24(scale_q)}; endcase end endfunction")
    emit_int_func(lines, "kscanon_case_phi_kind", [phi_kind] * len(CASES), phi_kind)

    lines.append("function [23:0] kscanon_y;")
    lines.append("input integer elem_idx; begin case(elem_idx)")
    for elem_idx, value in enumerate(y64_q):
        lines.append(f"  {elem_idx}: kscanon_y = {hex24(value)};")
    lines.append("  default: kscanon_y = 24'h000000; endcase end endfunction")

    lines.append("function [23:0] kscanon_x_final;")
    lines.append("input integer case_idx; input integer alg_idx; input integer elem_idx; begin case(((case_idx * KSCANON_GOLD_ALGS + alg_idx) * KSCANON_GOLD_MAX_N) + elem_idx)")
    for case_idx, (m_size, n_size, k_size) in enumerate(CASES):
        phi_q = fixed.make_phi(m_size, n_size, seed, scale_q)
        phi = [[value / float(1 << Q) for value in row] for row in phi_q]
        y = [value / float(1 << Q) for value in y64_q[:m_size]]
        canonical = run_all(phi, y, k_size, iht_step=1.0 / (1 << MU_SHIFT))
        for alg_idx, name in enumerate(ALGORITHM_NAMES):
            if name == "GP":
                x_q = fixed.gradient_pursuit(phi_q, y64_q[:m_size], k_size).x
            else:
                x_q = _q24(canonical[name].x)
            for elem_idx, value in enumerate(x_q):
                if value:
                    flat_key = ((case_idx * len(ALGORITHM_NAMES) + alg_idx) * 256) + elem_idx
                    lines.append(f"  {flat_key}: kscanon_x_final = {hex24(value)};")
    lines.append("  default: kscanon_x_final = 24'h000000; endcase end endfunction")

    generated = "\n".join(lines) + "\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generated, newline="\n")
    return generated


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output_path = args.output if args.output.is_absolute() else ROOT / args.output
    if args.check:
        temporary = output_path.with_suffix(output_path.suffix + ".tmp")
        generated = generate(temporary)
        existing = output_path.read_text() if output_path.exists() else None
        temporary.unlink()
        if existing != generated:
            raise SystemExit(f"canonical golden mismatch: {output_path}")
        print(f"canonical golden check PASS: {output_path}")
    else:
        generate(output_path)
        print(output_path)


if __name__ == "__main__":
    main()
