"""Generate the canonical, capacity-unlimited K-sweep golden include."""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    from .canonical_algorithms import run_all
    from . import generate_k_sweep_golden as hw
except ImportError:  # direct ``python models/golden/*.py`` execution
    from canonical_algorithms import run_all
    import generate_k_sweep_golden as hw


ROOT = hw.ROOT
IMMUTABLE = hw.IMMUTABLE
DEFAULT_OUT = ROOT / "verification" / "v2" / "run1" / "k_sweep_golden_canonical.vh"
Q = hw.Q
ALGORITHM_NAMES = list(hw.TB_ALG_NAMES)


def _q24(values: list[float]) -> list[int]:
    return [hw.quantize_float(value) for value in values]


def generate(output_path: Path) -> str:
    immutable = IMMUTABLE.read_text(errors="ignore")
    immutable_y = hw.parse_hex_func(immutable, "gold_y")
    seed = hw.parse_int_func(immutable, "gold_case_seed").get(0, 17)
    scale_q = hw.parse_hex_func(immutable, "gold_case_scale").get(0, 0x4000)
    phi_kind = hw.parse_hex_func(immutable, "gold_case_phi_kind").get(0, 0)
    y64_q = [hw.s24(immutable_y.get(idx, 0)) for idx in range(64)]

    lines = [
        "// Auto-generated by models/golden/generate_canonical_k_sweep.py",
        "// Canonical textbook references; no RTL merge-cap or PE scheduling limit.",
        "// IHT/HTP use step_size=1/8 to match the declared v2 numerical scale.",
        "// GP uses support expansion plus restricted-gradient line search.",
        "localparam integer KSCANON_GOLD_CASES = 8;",
        "localparam integer KSCANON_GOLD_ALGS = 8;",
        "localparam integer KSCANON_GOLD_MAX_N = 256;",
        "localparam integer KSCANON_GOLD_TOL = 512;",
    ]
    for case_idx, (m_size, n_size, k_size) in enumerate(hw.CASES):
        lines.extend([
            f"localparam integer KSCANON_CASE_{case_idx}_M = {m_size};",
            f"localparam integer KSCANON_CASE_{case_idx}_N = {n_size};",
            f"localparam integer KSCANON_CASE_{case_idx}_K = {k_size};",
        ])

    hw.emit_int_func(lines, "kscanon_case_m", [item[0] for item in hw.CASES], 0)
    hw.emit_int_func(lines, "kscanon_case_n", [item[1] for item in hw.CASES], 0)
    hw.emit_int_func(lines, "kscanon_case_k", [item[2] for item in hw.CASES], 0)
    hw.emit_int_func(lines, "kscanon_case_seed", [seed] * len(hw.CASES), seed)
    lines.append("function [23:0] kscanon_case_scale;")
    lines.append("input integer case_idx; begin case(case_idx)")
    for case_idx in range(len(hw.CASES)):
        lines.append(f"  {case_idx}: kscanon_case_scale = {hw.hex24(scale_q)};")
    lines.append(f"  default: kscanon_case_scale = {hw.hex24(scale_q)}; endcase end endfunction")
    hw.emit_int_func(lines, "kscanon_case_phi_kind", [phi_kind] * len(hw.CASES), phi_kind)

    lines.append("function [23:0] kscanon_y;")
    lines.append("input integer elem_idx; begin case(elem_idx)")
    for elem_idx, value in enumerate(y64_q):
        lines.append(f"  {elem_idx}: kscanon_y = {hw.hex24(value)};")
    lines.append("  default: kscanon_y = 24'h000000; endcase end endfunction")

    lines.append("function [23:0] kscanon_x_final;")
    lines.append("input integer case_idx; input integer alg_idx; input integer elem_idx; begin case(((case_idx * KSCANON_GOLD_ALGS + alg_idx) * KSCANON_GOLD_MAX_N) + elem_idx)")
    for case_idx, (m_size, n_size, k_size) in enumerate(hw.CASES):
        phi_q = hw.make_phi(m_size, n_size, seed, scale_q)
        phi = [[value / float(1 << Q) for value in row] for row in phi_q]
        y = [value / float(1 << Q) for value in y64_q[:m_size]]
        canonical = run_all(phi, y, k_size, iht_step=1.0 / (1 << hw.MU_SHIFT))
        for alg_idx, name in enumerate(ALGORITHM_NAMES):
            x_q = _q24(canonical[name].x)
            for elem_idx, value in enumerate(x_q):
                if value:
                    flat_key = ((case_idx * len(ALGORITHM_NAMES) + alg_idx) * 256) + elem_idx
                    lines.append(f"  {flat_key}: kscanon_x_final = {hw.hex24(value)};")
    lines.append("  default: kscanon_x_final = 24'h000000; endcase end endfunction")

    generated = "\n".join(lines) + "\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generated, newline="\n")
    return generated


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output_path = args.output if args.output.is_absolute() else ROOT / args.output
    if args.check:
        temporary = output_path.with_suffix(output_path.suffix + ".tmp")
        generated = generate(temporary)
        existing = output_path.read_text() if output_path.exists() else None
        temporary.unlink()
        if existing != generated:
            raise SystemExit(f"canonical golden mismatch: {output_path}")
        print(f"canonical golden check PASS: {output_path}")
    else:
        generate(output_path)
        print(output_path)


if __name__ == "__main__":
    main()
