module tb_operand_reader;
reg clk = 0;
reg [2231:0] stim;
wire [0:0] rst;
wire [0:0] cancel;
wire [0:0] req_valid;
wire [1:0] req_mode;
wire [0:0] req_trans;
wire [7:0] req_rows;
wire [10:0] req_cols;
wire [10:0] req_out;
wire [10:0] req_red;
wire [2:0] req_step;
wire [11:0] req_vec_base;
wire [1:0] req_vec_plane;
wire [17:0] req_scale;
wire [127:0] req_key;
wire [31:0] req_mat_generation;
wire [31:0] req_vec_generation;
wire [15:0] req_job;
wire [15:0] req_tag;
wire [7:0] req_fmt;
wire [0:0] req_last;
wire [0:0] mat_ready;
wire [0:0] mat_rsp_valid;
wire [575:0] mat_rsp_data;
wire [255:0] mat_rsp_masks;
wire [31:0] mat_rsp_mask;
wire [31:0] mat_rsp_generation;
wire [15:0] mat_rsp_job;
wire [15:0] mat_rsp_tag;
wire [7:0] mat_rsp_fmt;
wire [3:0] mat_rsp_fault;
wire [0:0] vec_ready;
wire [0:0] vec_rsp_valid;
wire [863:0] vec_rsp_data;
wire [31:0] vec_rsp_mask;
wire [31:0] vec_rsp_generation;
wire [15:0] vec_rsp_job;
wire [15:0] vec_rsp_tag;
wire [7:0] vec_rsp_fmt;
wire [3:0] vec_rsp_fault;
wire [0:0] rsp_ready;
wire [0:0] req_ready;
wire [0:0] mat_valid;
wire [0:0] mat_dense;
wire [31:0] mat_mask;
wire [287:0] mat_addr;
wire [127:0] mat_key;
wire [31:0] mat_generation;
wire [15:0] mem_job;
wire [15:0] mem_tag;
wire [7:0] mem_fmt;
wire [0:0] mat_rsp_ready;
wire [0:0] vec_valid;
wire [1:0] vec_plane;
wire [31:0] vec_mask;
wire [223:0] vec_addr;
wire [31:0] vec_generation;
wire [0:0] vec_rsp_ready;
wire [0:0] rsp_valid;
wire [863:0] rsp_mat;
wire [863:0] rsp_vec;
wire [31:0] rsp_mask;
wire [3:0] rsp_fault;
wire [15:0] rsp_job;
wire [15:0] rsp_tag;
wire [7:0] rsp_fmt;
wire [0:0] rsp_last;
assign {rst, cancel, req_valid, req_mode, req_trans, req_rows, req_cols, req_out, req_red, req_step, req_vec_base, req_vec_plane, req_scale, req_key, req_mat_generation, req_vec_generation, req_job, req_tag, req_fmt, req_last, mat_ready, mat_rsp_valid, mat_rsp_data, mat_rsp_masks, mat_rsp_mask, mat_rsp_generation, mat_rsp_job, mat_rsp_tag, mat_rsp_fmt, mat_rsp_fault, vec_ready, vec_rsp_valid, vec_rsp_data, vec_rsp_mask, vec_rsp_generation, vec_rsp_job, vec_rsp_tag, vec_rsp_fmt, vec_rsp_fault, rsp_ready} = stim;
operand_reader dut (.clk(clk), .rst(rst), .cancel(cancel), .req_valid(req_valid), .req_mode(req_mode), .req_trans(req_trans), .req_rows(req_rows), .req_cols(req_cols), .req_out(req_out), .req_red(req_red), .req_step(req_step), .req_vec_base(req_vec_base), .req_vec_plane(req_vec_plane), .req_scale(req_scale), .req_key(req_key), .req_mat_generation(req_mat_generation), .req_vec_generation(req_vec_generation), .req_job(req_job), .req_tag(req_tag), .req_fmt(req_fmt), .req_last(req_last), .mat_ready(mat_ready), .mat_rsp_valid(mat_rsp_valid), .mat_rsp_data(mat_rsp_data), .mat_rsp_masks(mat_rsp_masks), .mat_rsp_mask(mat_rsp_mask), .mat_rsp_generation(mat_rsp_generation), .mat_rsp_job(mat_rsp_job), .mat_rsp_tag(mat_rsp_tag), .mat_rsp_fmt(mat_rsp_fmt), .mat_rsp_fault(mat_rsp_fault), .vec_ready(vec_ready), .vec_rsp_valid(vec_rsp_valid), .vec_rsp_data(vec_rsp_data), .vec_rsp_mask(vec_rsp_mask), .vec_rsp_generation(vec_rsp_generation), .vec_rsp_job(vec_rsp_job), .vec_rsp_tag(vec_rsp_tag), .vec_rsp_fmt(vec_rsp_fmt), .vec_rsp_fault(vec_rsp_fault), .rsp_ready(rsp_ready), .req_ready(req_ready), .mat_valid(mat_valid), .mat_dense(mat_dense), .mat_mask(mat_mask), .mat_addr(mat_addr), .mat_key(mat_key), .mat_generation(mat_generation), .mem_job(mem_job), .mem_tag(mem_tag), .mem_fmt(mem_fmt), .mat_rsp_ready(mat_rsp_ready), .vec_valid(vec_valid), .vec_plane(vec_plane), .vec_mask(vec_mask), .vec_addr(vec_addr), .vec_generation(vec_generation), .vec_rsp_ready(vec_rsp_ready), .rsp_valid(rsp_valid), .rsp_mat(rsp_mat), .rsp_vec(rsp_vec), .rsp_mask(rsp_mask), .rsp_fault(rsp_fault), .rsp_job(rsp_job), .rsp_tag(rsp_tag), .rsp_fmt(rsp_fmt), .rsp_last(rsp_last));
integer src, dst, scanned, cycle;
reg [4095:0] src_path, dst_path;
initial begin
if (!$value$plusargs("src=%s", src_path)) $fatal(1, "missing vectors");
if (!$value$plusargs("dst=%s", dst_path)) $fatal(1, "missing trace");
src = $fopen(src_path, "r"); dst = $fopen(dst_path, "w");
if (!src || !dst) $fatal(1, "cannot open files");
cycle = 0;
while (!$feof(src)) begin
scanned = $fscanf(src, "%h", stim);
if (scanned == 1) begin
#4;
$fdisplay(dst, "%0d 0 %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h", cycle, req_ready, mat_valid, mat_dense, mat_mask, mat_addr, mat_key, mat_generation, mem_job, mem_tag, mem_fmt, mat_rsp_ready, vec_valid, vec_plane, vec_mask, vec_addr, vec_generation, vec_rsp_ready, rsp_valid, rsp_mat, rsp_vec, rsp_mask, rsp_fault, rsp_job, rsp_tag, rsp_fmt, rsp_last);
clk = 1; #1;
$fdisplay(dst, "%0d 1 %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h", cycle, req_ready, mat_valid, mat_dense, mat_mask, mat_addr, mat_key, mat_generation, mem_job, mem_tag, mem_fmt, mat_rsp_ready, vec_valid, vec_plane, vec_mask, vec_addr, vec_generation, vec_rsp_ready, rsp_valid, rsp_mat, rsp_vec, rsp_mask, rsp_fault, rsp_job, rsp_tag, rsp_fmt, rsp_last);
#4; clk = 0; cycle = cycle + 1;
end else if (!$feof(src)) $fatal(1, "bad vector row");
end
$fclose(src); $fclose(dst);
$display("PASS cycles=%0d", cycle); $finish;
end
initial begin #100000000; $fatal(1, "timeout"); end
endmodule
