module tb_ram_reader;
reg clk = 0;
reg [2115:0] stim;
wire [0:0] rst;
wire [0:0] cancel;
wire [0:0] req_valid;
wire [1:0] req_mode;
wire [0:0] req_trans;
wire [7:0] req_rows;
wire [10:0] req_cols;
wire [10:0] req_out;
wire [10:0] req_red;
wire [2:0] req_step;
wire [11:0] req_vec_base;
wire [1:0] req_vec_plane;
wire [17:0] req_scale;
wire [127:0] req_key;
wire [31:0] req_mat_generation;
wire [31:0] req_vec_generation;
wire [15:0] req_job;
wire [15:0] req_tag;
wire [7:0] req_fmt;
wire [0:0] req_last;
wire [0:0] rsp_ready;
wire [0:0] mat_req_en;
wire [0:0] mat_rsp_en;
wire [0:0] vec_req_en;
wire [0:0] vec_rsp_en;
wire [0:0] b_begin_valid;
wire [7:0] b_begin_rows;
wire [6:0] b_begin_cols;
wire [127:0] b_begin_key;
wire [31:0] b_begin_generation;
wire [15:0] b_begin_job;
wire [7:0] b_begin_fmt;
wire [0:0] b_fill_valid;
wire [6:0] b_fill_slot;
wire [1:0] b_fill_block;
wire [31:0] b_fill_mask;
wire [575:0] b_fill_data;
wire [0:0] b_fill_last;
wire [0:0] v_begin_valid;
wire [1:0] v_begin_plane;
wire [12:0] v_begin_length;
wire [31:0] v_begin_generation;
wire [15:0] v_begin_job;
wire [7:0] v_begin_fmt;
wire [0:0] v_fill_valid;
wire [6:0] v_fill_block;
wire [31:0] v_fill_mask;
wire [863:0] v_fill_data;
wire [0:0] v_fill_last;
wire [0:0] b_begin_ready;
wire [0:0] b_fill_ready;
wire [0:0] b_loading;
wire [0:0] b_cache_valid;
wire [3:0] b_load_fault;
wire [0:0] v_begin_ready;
wire [0:0] v_fill_ready;
wire [0:0] v_loading;
wire [2:0] v_plane_valid;
wire [3:0] v_load_fault;
wire [0:0] req_ready;
wire [0:0] mat_valid;
wire [0:0] mat_dense;
wire [31:0] mat_mask;
wire [287:0] mat_addr;
wire [127:0] mat_key;
wire [31:0] mat_generation;
wire [15:0] mem_job;
wire [15:0] mem_tag;
wire [7:0] mem_fmt;
wire [0:0] mat_rsp_ready;
wire [0:0] vec_valid;
wire [1:0] vec_plane;
wire [31:0] vec_mask;
wire [223:0] vec_addr;
wire [31:0] vec_generation;
wire [0:0] vec_rsp_ready;
wire [0:0] rsp_valid;
wire [863:0] rsp_mat;
wire [863:0] rsp_vec;
wire [31:0] rsp_mask;
wire [3:0] rsp_fault;
wire [15:0] rsp_job;
wire [15:0] rsp_tag;
wire [7:0] rsp_fmt;
wire [0:0] rsp_last;
assign {rst, cancel, req_valid, req_mode, req_trans, req_rows, req_cols, req_out, req_red, req_step, req_vec_base, req_vec_plane, req_scale, req_key, req_mat_generation, req_vec_generation, req_job, req_tag, req_fmt, req_last, rsp_ready, mat_req_en, mat_rsp_en, vec_req_en, vec_rsp_en, b_begin_valid, b_begin_rows, b_begin_cols, b_begin_key, b_begin_generation, b_begin_job, b_begin_fmt, b_fill_valid, b_fill_slot, b_fill_block, b_fill_mask, b_fill_data, b_fill_last, v_begin_valid, v_begin_plane, v_begin_length, v_begin_generation, v_begin_job, v_begin_fmt, v_fill_valid, v_fill_block, v_fill_mask, v_fill_data, v_fill_last} = stim;
wire [0:0] b_rd_valid;
wire [31:0] b_rd_mask;
wire [287:0] b_rd_addr;
wire [127:0] b_rd_key;
wire [31:0] b_rd_generation;
wire [15:0] b_rd_job;
wire [15:0] b_rd_tag;
wire [7:0] b_rd_fmt;
wire [0:0] b_rsp_ready;
wire [0:0] b_rd_ready;
wire [0:0] b_rsp_valid;
wire [575:0] b_rsp_data;
wire [31:0] b_rsp_mask;
wire [31:0] b_rsp_generation;
wire [15:0] b_rsp_job;
wire [15:0] b_rsp_tag;
wire [7:0] b_rsp_fmt;
wire [3:0] b_rsp_fault;
support_matrix_cache b_ram (.clk(clk), .rst(rst), .cancel(cancel), .begin_valid(b_begin_valid), .begin_rows(b_begin_rows), .begin_cols(b_begin_cols), .begin_key(b_begin_key), .begin_generation(b_begin_generation), .begin_job(b_begin_job), .begin_fmt(b_begin_fmt), .fill_valid(b_fill_valid), .fill_slot(b_fill_slot), .fill_block(b_fill_block), .fill_mask(b_fill_mask), .fill_data(b_fill_data), .fill_last(b_fill_last), .rd_valid(b_rd_valid), .rd_mask(b_rd_mask), .rd_addr(b_rd_addr), .rd_key(b_rd_key), .rd_generation(b_rd_generation), .rd_job(b_rd_job), .rd_tag(b_rd_tag), .rd_fmt(b_rd_fmt), .rsp_ready(b_rsp_ready), .begin_ready(b_begin_ready), .fill_ready(b_fill_ready), .loading(b_loading), .cache_valid(b_cache_valid), .load_fault(b_load_fault), .rd_ready(b_rd_ready), .rsp_valid(b_rsp_valid), .rsp_data(b_rsp_data), .rsp_mask(b_rsp_mask), .rsp_generation(b_rsp_generation), .rsp_job(b_rsp_job), .rsp_tag(b_rsp_tag), .rsp_fmt(b_rsp_fmt), .rsp_fault(b_rsp_fault));
assign b_rd_valid = mat_valid & mat_req_en;
assign b_rd_mask = mat_mask;
assign b_rd_addr = mat_addr;
assign b_rd_generation = mat_generation;
assign b_rd_job = mem_job;
assign b_rd_tag = mem_tag;
assign b_rd_fmt = mem_fmt;
assign b_rsp_ready = mat_rsp_ready & mat_rsp_en;
assign b_rd_key = mat_key;
wire [1:0] v_rd_valid;
wire [3:0] v_rd_plane;
wire [63:0] v_rd_mask;
wire [447:0] v_rd_addr;
wire [63:0] v_rd_generation;
wire [31:0] v_rd_job;
wire [31:0] v_rd_tag;
wire [15:0] v_rd_fmt;
wire [1:0] v_rsp_ready;
wire [1:0] v_rd_ready;
wire [1:0] v_rsp_valid;
wire [1727:0] v_rsp_data;
wire [63:0] v_rsp_mask;
wire [63:0] v_rsp_generation;
wire [31:0] v_rsp_job;
wire [31:0] v_rsp_tag;
wire [15:0] v_rsp_fmt;
wire [7:0] v_rsp_fault;
vector_store v_ram (.clk(clk), .rst(rst), .cancel(cancel), .begin_valid(v_begin_valid), .begin_plane(v_begin_plane), .begin_length(v_begin_length), .begin_generation(v_begin_generation), .begin_job(v_begin_job), .begin_fmt(v_begin_fmt), .fill_valid(v_fill_valid), .fill_block(v_fill_block), .fill_mask(v_fill_mask), .fill_data(v_fill_data), .fill_last(v_fill_last), .rd_valid(v_rd_valid), .rd_plane(v_rd_plane), .rd_mask(v_rd_mask), .rd_addr(v_rd_addr), .rd_generation(v_rd_generation), .rd_job(v_rd_job), .rd_tag(v_rd_tag), .rd_fmt(v_rd_fmt), .rsp_ready(v_rsp_ready), .begin_ready(v_begin_ready), .fill_ready(v_fill_ready), .loading(v_loading), .plane_valid(v_plane_valid), .load_fault(v_load_fault), .rd_ready(v_rd_ready), .rsp_valid(v_rsp_valid), .rsp_data(v_rsp_data), .rsp_mask(v_rsp_mask), .rsp_generation(v_rsp_generation), .rsp_job(v_rsp_job), .rsp_tag(v_rsp_tag), .rsp_fmt(v_rsp_fmt), .rsp_fault(v_rsp_fault));
assign v_rd_valid = {1'b0, (vec_valid & vec_req_en)};
assign v_rd_mask = {32'b0, (vec_mask)};
assign v_rd_addr = {224'b0, (vec_addr)};
assign v_rd_generation = {32'b0, (vec_generation)};
assign v_rd_job = {16'b0, (mem_job)};
assign v_rd_tag = {16'b0, (mem_tag)};
assign v_rd_fmt = {8'b0, (mem_fmt)};
assign v_rsp_ready = {1'b0, (vec_rsp_ready & vec_rsp_en)};
assign v_rd_plane = {2'b0, (vec_plane)};
operand_reader dut (.clk(clk), .rst(rst), .cancel(cancel), .req_valid(req_valid), .req_mode(req_mode), .req_trans(req_trans), .req_rows(req_rows), .req_cols(req_cols), .req_out(req_out), .req_red(req_red), .req_step(req_step), .req_vec_base(req_vec_base), .req_vec_plane(req_vec_plane), .req_scale(req_scale), .req_key(req_key), .req_mat_generation(req_mat_generation), .req_vec_generation(req_vec_generation), .req_job(req_job), .req_tag(req_tag), .req_fmt(req_fmt), .req_last(req_last), .mat_ready(b_rd_ready[0] & mat_req_en), .mat_rsp_valid(b_rsp_valid[0] & mat_rsp_en), .mat_rsp_data(b_rsp_data[575:0]), .mat_rsp_masks(256'b0), .mat_rsp_mask(b_rsp_mask[31:0]), .mat_rsp_generation(b_rsp_generation[31:0]), .mat_rsp_job(b_rsp_job[15:0]), .mat_rsp_tag(b_rsp_tag[15:0]), .mat_rsp_fmt(b_rsp_fmt[7:0]), .mat_rsp_fault(b_rsp_fault[3:0]), .vec_ready(v_rd_ready[0] & vec_req_en), .vec_rsp_valid(v_rsp_valid[0] & vec_rsp_en), .vec_rsp_data(v_rsp_data[863:0]), .vec_rsp_mask(v_rsp_mask[31:0]), .vec_rsp_generation(v_rsp_generation[31:0]), .vec_rsp_job(v_rsp_job[15:0]), .vec_rsp_tag(v_rsp_tag[15:0]), .vec_rsp_fmt(v_rsp_fmt[7:0]), .vec_rsp_fault(v_rsp_fault[3:0]), .rsp_ready(rsp_ready), .req_ready(req_ready), .mat_valid(mat_valid), .mat_dense(mat_dense), .mat_mask(mat_mask), .mat_addr(mat_addr), .mat_key(mat_key), .mat_generation(mat_generation), .mem_job(mem_job), .mem_tag(mem_tag), .mem_fmt(mem_fmt), .mat_rsp_ready(mat_rsp_ready), .vec_valid(vec_valid), .vec_plane(vec_plane), .vec_mask(vec_mask), .vec_addr(vec_addr), .vec_generation(vec_generation), .vec_rsp_ready(vec_rsp_ready), .rsp_valid(rsp_valid), .rsp_mat(rsp_mat), .rsp_vec(rsp_vec), .rsp_mask(rsp_mask), .rsp_fault(rsp_fault), .rsp_job(rsp_job), .rsp_tag(rsp_tag), .rsp_fmt(rsp_fmt), .rsp_last(rsp_last));
integer src, dst, scanned, cycle;
reg [4095:0] src_path, dst_path;
initial begin
if (!$value$plusargs("src=%s", src_path)) $fatal(1, "missing vectors");
if (!$value$plusargs("dst=%s", dst_path)) $fatal(1, "missing trace");
src = $fopen(src_path, "r"); dst = $fopen(dst_path, "w");
if (!src || !dst) $fatal(1, "cannot open files");
cycle = 0;
while (!$feof(src)) begin
scanned = $fscanf(src, "%h", stim);
if (scanned == 1) begin
#4;
$fdisplay(dst, "%0d 0 %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h", cycle, b_begin_ready, b_fill_ready, b_loading, b_cache_valid, b_load_fault, v_begin_ready, v_fill_ready, v_loading, v_plane_valid, v_load_fault, req_ready, mat_valid, mat_dense, mat_mask, mat_addr, mat_key, mat_generation, mem_job, mem_tag, mem_fmt, mat_rsp_ready, vec_valid, vec_plane, vec_mask, vec_addr, vec_generation, vec_rsp_ready, rsp_valid, rsp_mat, rsp_vec, rsp_mask, rsp_fault, rsp_job, rsp_tag, rsp_fmt, rsp_last);
clk = 1; #1;
$fdisplay(dst, "%0d 1 %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h", cycle, b_begin_ready, b_fill_ready, b_loading, b_cache_valid, b_load_fault, v_begin_ready, v_fill_ready, v_loading, v_plane_valid, v_load_fault, req_ready, mat_valid, mat_dense, mat_mask, mat_addr, mat_key, mat_generation, mem_job, mem_tag, mem_fmt, mat_rsp_ready, vec_valid, vec_plane, vec_mask, vec_addr, vec_generation, vec_rsp_ready, rsp_valid, rsp_mat, rsp_vec, rsp_mask, rsp_fault, rsp_job, rsp_tag, rsp_fmt, rsp_last);
clk = 0; #1; cycle = cycle+1;
end
end
$fclose(src); $fclose(dst);
$display("PASS cycles=%0d", cycle); $finish;
end
endmodule

