if {$argc < 2} { error "usage: check_m8.tcl <repo_root> <report_dir>" }
set repo_root [file normalize [lindex $argv 0]]; set report_dir [file normalize [lindex $argv 1]]; file mkdir $report_dir
set part_name "xczu7ev-ffvc1156-2-e"; set include_dir [file join $repo_root rtl v3 include]
set rtl_sources [list \
[file join $repo_root rtl v3 memory recon_sdp_ram.v] [file join $repo_root rtl v3 memory recon_1w2r_ram.v] [file join $repo_root rtl v3 memory support_coefficient_stripe_store.v] [file join $repo_root rtl v3 reconstruction_control resident_execution_state.v] \
[file join $repo_root rtl v3 data_movement vector_scratchpad.v] [file join $repo_root rtl v3 data_movement scratchpad_subsystem.v] [file join $repo_root rtl v3 data_movement vector_stream_engine.v] [file join $repo_root rtl v3 data_movement scratchpad_word_codec.v] [file join $repo_root rtl v3 data_movement vector_codec_write_subsystem.v] [file join $repo_root rtl v3 data_movement vector_ingress_adapter.v] [file join $repo_root rtl v3 data_movement normalized_result_writeback.v] \
[file join $repo_root rtl v3 cgra stream_context_router.v] [file join $repo_root rtl v3 cgra pe_alu.v] [file join $repo_root rtl v3 cgra phi_pe_alu.v] [file join $repo_root rtl v3 cgra pe_local_register_file.v] [file join $repo_root rtl v3 cgra registered_switchbox.v] [file join $repo_root rtl v3 cgra pe_tile.v] [file join $repo_root rtl v3 cgra phi_pe_tile.v] [file join $repo_root rtl v3 cgra cgra_row.v] [file join $repo_root rtl v3 cgra cgra_cluster.v] [file join $repo_root rtl v3 cgra cgra_cluster_pair.v] [file join $repo_root rtl v3 cgra cgra_result_buffer.v] [file join $repo_root rtl v3 cgra cgra_result_capture_adapter.v] [file join $repo_root rtl v3 cgra cgra_execution_fabric.v] \
[file join $repo_root rtl v3 phi phi_request_queue.v] [file join $repo_root rtl v3 phi threefry2x32_folded_pipeline.v] [file join $repo_root rtl v3 phi phi_symbol_builder.v] [file join $repo_root rtl v3 phi phi_response_gearbox.v] [file join $repo_root rtl v3 phi phi_symbol_generator.v] [file join $repo_root rtl v3 phi support_phi_symbol_cache.v] [file join $repo_root rtl v3 phi phi_stream_provider.v] [file join $repo_root rtl v3 phi phi_stream_subsystem.v] [file join $repo_root rtl v3 phi phi_operator_normalizer.v] [file join $repo_root rtl v3 phi phi_lane_normalization_flow.v] [file join $repo_root rtl v3 phi phi_column_flow.v] \
[file join $repo_root rtl v3 arithmetic cluster_reduction_unit.v] [file join $repo_root rtl v3 arithmetic global_reduction_merge.v] [file join $repo_root rtl v3 arithmetic reduction_pipeline.v] [file join $repo_root rtl v3 arithmetic scalar_register_file.v] [file join $repo_root rtl v3 arithmetic scalar_state_subsystem.v] [file join $repo_root rtl v3 arithmetic scalar_function_unit.v] [file join $repo_root rtl v3 arithmetic shared_vector_arithmetic_unit.v] [file join $repo_root rtl v3 arithmetic shared_vector_pipeline.v] [file join $repo_root rtl v3 arithmetic array_resource_router.v] [file join $repo_root rtl v3 arithmetic m5_arithmetic_subsystem.v] \
[file join $repo_root rtl v3 selection topk_selection_unit.v] [file join $repo_root rtl v3 selection proxy_candidate_collector.v] [file join $repo_root rtl v3 selection vector_candidate_serializer.v] [file join $repo_root rtl v3 selection candidate_stream_adapter.v] [file join $repo_root rtl v3 selection support_vector_rebuilder.v] [file join $repo_root rtl v3 selection support_refinement_adapter.v] [file join $repo_root rtl v3 selection support_workspace.v] [file join $repo_root rtl v3 selection support_state_manager.v] [file join $repo_root rtl v3 selection support_coefficient_remapper.v] [file join $repo_root rtl v3 refinement certificate_limit_unit.v] [file join $repo_root rtl v3 refinement normal_residual_checker.v] [file join $repo_root rtl v3 debug operator_fault_monitor.v] [file join $repo_root rtl v3 debug operator_fault_event_encoder.v] [file join $repo_root rtl v3 integration m8_resource_dispatcher.v] [file join $repo_root rtl v3 integration operator_flow_control.v] [file join $repo_root rtl v3 integration m8_operator_harness.v]]
create_project -in_memory -part $part_name; source [file join $repo_root scripts synth load_v3_xpm_memory.tcl]; set_property target_language Verilog [current_project]; set_property include_dirs [list $include_dir] [current_fileset]; read_verilog -sv $rtl_sources
read_xdc [file join $repo_root constraints v3 m8_ooc.xdc]; synth_design -top m8_operator_harness -part $part_name -mode out_of_context -flatten_hierarchy rebuilt
write_checkpoint -force [file join $report_dir post_synth.dcp]; report_utilization -file [file join $report_dir utilization.rpt]; report_timing_summary -delay_type max -max_paths 10 -file [file join $report_dir timing_summary.rpt]; report_drc -file [file join $report_dir drc.rpt]; check_timing -verbose -file [file join $report_dir check_timing.rpt]
set paths [get_timing_paths -delay_type max -max_paths 1 -nworst 1]; if {[llength $paths] == 0} {error "no setup path"}; set wns [get_property SLACK [lindex $paths 0]]
set lut [llength [get_cells -quiet -hier -filter {REF_NAME =~ LUT*}]]; set ff [llength [get_cells -quiet -hier -filter {REF_NAME =~ FD*}]]; set r36 [llength [get_cells -quiet -hier -filter {REF_NAME =~ RAMB36*}]]; set r18 [llength [get_cells -quiet -hier -filter {REF_NAME =~ RAMB18*}]]; set dsp [llength [get_cells -quiet -hier -filter {REF_NAME =~ DSP48*}]]; set gate_pass [expr {$wns >= 1.0}]
set fp [open [file join $report_dir summary.txt] w]; puts $fp "part=$part_name"; puts $fp "top=m8_operator_harness"; puts $fp "clock_period_ns=6.667"; puts $fp "clock_uncertainty_ns=0.200"; puts $fp "post_synth_wns_ns=$wns"; puts $fp "wns_gate_min_ns=1.0"; puts $fp "wns_gate_pass=$gate_pass"; puts $fp "lut_count=$lut"; puts $fp "ff_count=$ff"; puts $fp "ramb36_count=$r36"; puts $fp "ramb18_count=$r18"; puts $fp "dsp48_count=$dsp"; close $fp
if {!$gate_pass} {error "m8_operator_harness WNS below +1.0 ns: $wns"}; puts "M8 synthesis PASS WNS=$wns LUT=$lut FF=$ff BRAM36=$r36 BRAM18=$r18 DSP=$dsp"
