`ifndef CSR_PE_INTERFACE_VH
`define CSR_PE_INTERFACE_VH
`define CSR_PE_S_W 27
`define CSR_PE_S_F 22
`define CSR_PE_C_W 18
`define CSR_PE_C_F 16
`define CSR_PE_ACC_W 64
`define CSR_PE_SPLIT 17
`define CSR_PE_OP_W 5
`define CSR_PE_FAULT_W 4
`define CSR_PE_JOB_W 16
`define CSR_PE_TAG_W 16
`define CSR_PE_FMT_W 8
`define CSR_PE_ROUTE_W 3
`define CSR_PE_ROWS 4
`define CSR_PE_COLS 4
`define CSR_PE_TILES 32
`define CSR_PE_OP_HOLD 0
`define CSR_PE_OP_MOV 1
`define CSR_PE_OP_ADD 2
`define CSR_PE_OP_SUB 3
`define CSR_PE_OP_ABS 4
`define CSR_PE_OP_CMP_S 5
`define CSR_PE_OP_CMP_U 6
`define CSR_PE_OP_SELECT 7
`define CSR_PE_OP_MUL 8
`define CSR_PE_OP_MAC 9
`define CSR_PE_OP_ACC_CLEAR 10
`define CSR_PE_OP_ACC_READ 11
`define CSR_PE_OP_ACC_ADD 12
`define CSR_PE_OP_AND 13
`define CSR_PE_OP_OR 14
`define CSR_PE_OP_XOR 15
`define CSR_PE_OP_NOT 16
`define CSR_PE_FAULT_NONE 0
`define CSR_PE_FAULT_SAT 1
`define CSR_PE_FAULT_ACC 2
`define CSR_PE_FAULT_OP 3
`define CSR_PE_FAULT_MODE 4
`define CSR_PE_FAULT_COEFF 5
`define CSR_PE_ROUTE_NONE 0
`define CSR_PE_ROUTE_VALUE 1
`define CSR_PE_ROUTE_ACC 2
`define CSR_PE_ROUTE_RESULT 3
`define CSR_PE_ROUTE_FAULT_NONE 0
`define CSR_PE_ROUTE_FAULT_SEL 1
`define CSR_PE_ROUTE_FAULT_EDGE 2
`define CSR_PE_ROUTE_FAULT_SRC 3
`endif
