module cgra_soc_top #(
    parameter integer AXIL_AW = 15,
    parameter integer AXIL_DW = 32,
    parameter integer AXI_AW  = 32,
    parameter integer AXI_DW  = 32,
    parameter integer NCTX = 2048,
    parameter integer IDX_W = 10,
    parameter integer SPARSE_MAX_N = 256,
    parameter integer SPARSE_MAX_K = 16
)(
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ap_clk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF s_axi_control:m_axi_gmem, ASSOCIATED_RESET ap_rst_n" *)
    input  wire                 ap_clk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ap_rst_n RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire                 ap_rst_n,

    input  wire [AXIL_AW-1:0]   s_axi_control_awaddr,
    input  wire                 s_axi_control_awvalid,
    output wire                 s_axi_control_awready,
    input  wire [AXIL_DW-1:0]   s_axi_control_wdata,
    input  wire [AXIL_DW/8-1:0] s_axi_control_wstrb,
    input  wire                 s_axi_control_wvalid,
    output wire                 s_axi_control_wready,
    output wire [1:0]           s_axi_control_bresp,
    output wire                 s_axi_control_bvalid,
    input  wire                 s_axi_control_bready,
    input  wire [AXIL_AW-1:0]   s_axi_control_araddr,
    input  wire                 s_axi_control_arvalid,
    output wire                 s_axi_control_arready,
    output wire [AXIL_DW-1:0]   s_axi_control_rdata,
    output wire [1:0]           s_axi_control_rresp,
    output wire                 s_axi_control_rvalid,
    input  wire                 s_axi_control_rready,

    output wire [AXI_AW-1:0]    m_axi_gmem_araddr,
    output wire [7:0]           m_axi_gmem_arlen,
    output wire [2:0]           m_axi_gmem_arsize,
    output wire [1:0]           m_axi_gmem_arburst,
    output wire                 m_axi_gmem_arvalid,
    input  wire                 m_axi_gmem_arready,
    input  wire [AXI_DW-1:0]    m_axi_gmem_rdata,
    input  wire [1:0]           m_axi_gmem_rresp,
    input  wire                 m_axi_gmem_rvalid,
    input  wire                 m_axi_gmem_rlast,
    output wire                 m_axi_gmem_rready,
    output wire [AXI_AW-1:0]    m_axi_gmem_awaddr,
    output wire [7:0]           m_axi_gmem_awlen,
    output wire [2:0]           m_axi_gmem_awsize,
    output wire [1:0]           m_axi_gmem_awburst,
    output wire                 m_axi_gmem_awvalid,
    input  wire                 m_axi_gmem_awready,
    output wire [AXI_DW-1:0]    m_axi_gmem_wdata,
    output wire [AXI_DW/8-1:0]  m_axi_gmem_wstrb,
    output wire                 m_axi_gmem_wlast,
    output wire                 m_axi_gmem_wvalid,
    input  wire                 m_axi_gmem_wready,
    input  wire [1:0]           m_axi_gmem_bresp,
    input  wire                 m_axi_gmem_bvalid,
    output wire                 m_axi_gmem_bready,

    output wire                 interrupt
);
    wire irq_done;
    wire irq_error;

    cgra_top #(
        .AXIL_AW(AXIL_AW),
        .AXIL_DW(AXIL_DW),
        .AXI_AW(AXI_AW),
        .AXI_DW(AXI_DW),
        .NCTX(NCTX),
        .IDX_W(IDX_W),
        .SPARSE_MAX_N(SPARSE_MAX_N),
        .SPARSE_MAX_K(SPARSE_MAX_K)
    ) u_cgra_top (
        .clk(ap_clk),
        .rst_n(ap_rst_n),
        .s_axi_awaddr(s_axi_control_awaddr),
        .s_axi_awvalid(s_axi_control_awvalid),
        .s_axi_awready(s_axi_control_awready),
        .s_axi_wdata(s_axi_control_wdata),
        .s_axi_wstrb(s_axi_control_wstrb),
        .s_axi_wvalid(s_axi_control_wvalid),
        .s_axi_wready(s_axi_control_wready),
        .s_axi_bresp(s_axi_control_bresp),
        .s_axi_bvalid(s_axi_control_bvalid),
        .s_axi_bready(s_axi_control_bready),
        .s_axi_araddr(s_axi_control_araddr),
        .s_axi_arvalid(s_axi_control_arvalid),
        .s_axi_arready(s_axi_control_arready),
        .s_axi_rdata(s_axi_control_rdata),
        .s_axi_rresp(s_axi_control_rresp),
        .s_axi_rvalid(s_axi_control_rvalid),
        .s_axi_rready(s_axi_control_rready),
        .m_axi_araddr(m_axi_gmem_araddr),
        .m_axi_arlen(m_axi_gmem_arlen),
        .m_axi_arsize(m_axi_gmem_arsize),
        .m_axi_arburst(m_axi_gmem_arburst),
        .m_axi_arvalid(m_axi_gmem_arvalid),
        .m_axi_arready(m_axi_gmem_arready),
        .m_axi_rdata(m_axi_gmem_rdata),
        .m_axi_rresp(m_axi_gmem_rresp),
        .m_axi_rvalid(m_axi_gmem_rvalid),
        .m_axi_rlast(m_axi_gmem_rlast),
        .m_axi_rready(m_axi_gmem_rready),
        .m_axi_awaddr(m_axi_gmem_awaddr),
        .m_axi_awlen(m_axi_gmem_awlen),
        .m_axi_awsize(m_axi_gmem_awsize),
        .m_axi_awburst(m_axi_gmem_awburst),
        .m_axi_awvalid(m_axi_gmem_awvalid),
        .m_axi_awready(m_axi_gmem_awready),
        .m_axi_wdata(m_axi_gmem_wdata),
        .m_axi_wstrb(m_axi_gmem_wstrb),
        .m_axi_wlast(m_axi_gmem_wlast),
        .m_axi_wvalid(m_axi_gmem_wvalid),
        .m_axi_wready(m_axi_gmem_wready),
        .m_axi_bresp(m_axi_gmem_bresp),
        .m_axi_bvalid(m_axi_gmem_bvalid),
        .m_axi_bready(m_axi_gmem_bready),
        .irq_done(irq_done),
        .irq_error(irq_error)
    );

    assign interrupt = irq_done | irq_error;
endmodule
