`ifndef ARCHITECTURE_GUARD_DEFS_VH
`define ARCHITECTURE_GUARD_DEFS_VH
// Generated from architecture_configuration.json. Do not edit.
`define RECON_ARCHITECTURE_HASH 256'h9d5b2dcd753df7d36d458f8d5071bb9fa87289a2dd2671b852f93621367ea072
`define RECON_TILE_OPERATION_LEGAL_MASK 32'h01feffff
`define RECON_RESOURCE_OPERATION_LEGAL_MASK 32'h03ffffff
`define RECON_RESOURCE_OPERATION_IMPLEMENTED_MASK 32'h03f17fef
`define RECON_RESOURCE_OPERATION_RESERVED_FAULT_MASK 32'h00028000
`define RECON_ROUTE_SOURCE_LEGAL_MASK 8'hbf
`define RECON_NEXT_PC_MODE_LEGAL_MASK 8'h3f
`define RECON_PHASE_OPERATION_LEGAL_MASK 8'h3f
`define RECON_PHASE_CONDITION_LEGAL_MASK 16'h3fff
`define RECON_PHASE_ENTRY_PC                             8'd0
`define RECON_CONTEXT_ERROR_ARRAY_CONTROL                8'd96
`define RECON_CONTEXT_ERROR_TILE_OPERATION               8'd97
`define RECON_CONTEXT_ERROR_ROUTE_CAPACITY               8'd98
`define RECON_CONTEXT_ERROR_STREAM_CONTRACT              8'd99
`define RECON_CONTEXT_ERROR_RESOURCE_CONTRACT            8'd100
`define RECON_CONTEXT_ERROR_GUARANTEED_COMMIT            8'd101
`define RECON_CONTEXT_ERROR_PHASE_INSTRUCTION            8'd102
`define RECON_CONTEXT_ERROR_MEMORY_CONFIGURATION         8'd103
`define RECON_CONTEXT_ERROR_IMAGE_WRITE                  8'd105
`define RECON_CONTEXT_ERROR_IMAGE_UNAVAILABLE            8'd104
`endif
