`ifndef RECON_LOADER_CONTROL_DEFS_VH
`define RECON_LOADER_CONTROL_DEFS_VH

`define RECON_LOADER_CSR_IDENTIFICATION       12'h000
`define RECON_LOADER_CSR_VERSION              12'h004
`define RECON_LOADER_CSR_COMMAND              12'h008
`define RECON_LOADER_CSR_STATUS               12'h00c
`define RECON_LOADER_CSR_DETAIL               12'h010

`define RECON_LOADER_CSR_IMAGE_META           12'h020
`define RECON_LOADER_CSR_IMAGE_DATA_LO        12'h024
`define RECON_LOADER_CSR_IMAGE_DATA_MID       12'h028
`define RECON_LOADER_CSR_IMAGE_DATA_HI        12'h02c

`define RECON_LOADER_CSR_MEMORY_META          12'h030
`define RECON_LOADER_CSR_MEMORY_DATA_LO       12'h034
`define RECON_LOADER_CSR_MEMORY_DATA_HI       12'h038

`define RECON_LOADER_CSR_SCALAR_META          12'h040
`define RECON_LOADER_CSR_SCALAR_DATA_LO       12'h044
`define RECON_LOADER_CSR_SCALAR_DATA_HI       12'h048

`define RECON_LOADER_CSR_SCRATCH_META         12'h050
`define RECON_LOADER_CSR_SCRATCH_DATA_LO      12'h054
`define RECON_LOADER_CSR_SCRATCH_DATA_MID     12'h058
`define RECON_LOADER_CSR_SCRATCH_DATA_HI      12'h05c

`define RECON_LOADER_CSR_PRELOAD_SRC_LO       12'h060
`define RECON_LOADER_CSR_PRELOAD_SRC_HI       12'h064
`define RECON_LOADER_CSR_PRELOAD_META         12'h068
`define RECON_LOADER_CSR_PRELOAD_CFG_LO       12'h06c
`define RECON_LOADER_CSR_PRELOAD_CFG_HI       12'h070

`define RECON_LOADER_COMMAND_IMAGE_WRITE      3'd1
`define RECON_LOADER_COMMAND_IMAGE_FINALIZE   3'd2
`define RECON_LOADER_COMMAND_MEMORY_WRITE     3'd3
`define RECON_LOADER_COMMAND_SCALAR_PRELOAD   3'd4
`define RECON_LOADER_COMMAND_SCALAR_CLEAR     3'd5
`define RECON_LOADER_COMMAND_SCRATCH_WRITE    3'd6
`define RECON_LOADER_COMMAND_SCRATCH_PRELOAD  3'd7

`define RECON_LOADER_IDENTIFICATION           32'h4c445233
`define RECON_LOADER_VERSION                  32'h00010000

`endif
