`ifndef RUN_CONFIGURATION_DEFS_VH
`define RUN_CONFIGURATION_DEFS_VH
// Generated run-configuration block revision 6. Do not edit.
`define RECON_RUN_CONFIGURATION_MAGIC                    16'd17234
`define RECON_RUN_CONFIGURATION_WORDS                    16
`define RECON_RUN_CONFIGURATION_BYTES                    64
`define RECON_RUN_CONFIGURATION_BITS                     512
`define RECON_PHI_DATA_NORMALIZER_MAX_EXPONENT           11
`define RECON_REFINEMENT_PROFILE_STRICT_PAPER            2'd0
`define RECON_REFINEMENT_PROFILE_BALANCED_VARIANT        2'd1
`define RECON_REFINEMENT_PROFILE_FAST_VARIANT            2'd2
`define RECON_MATRIX_KIND_DENSE_RADEMACHER               2'd0
`define RECON_MATRIX_KIND_FIXED_COLUMN_WEIGHT_EXPERIMENTAL 2'd1
`define RECON_RESULT_MODE_DENSE                          2'd0
`define RECON_RESULT_MODE_SPARSE                         2'd1
`define RECON_RESULT_MODE_BOTH                           2'd2
`define RECON_TERMINATION_MODE_NORMAL                    1'd0
`define RECON_TERMINATION_MODE_FORCE_OUTER_ITERATIONS    1'd1
`define RECON_RUN_CONFIGURATION_W2_REFINEMENT_PROFILE_MSB 31
`define RECON_RUN_CONFIGURATION_W2_REFINEMENT_PROFILE_LSB 30
`define RECON_RUN_CONFIGURATION_W2_TERMINATION_MODE_MSB 29
`define RECON_RUN_CONFIGURATION_W2_TERMINATION_MODE_LSB 29
`endif
